---
title: "Bacteria Subsection and plotting"
author: "Andreas Norlin"
date: "2023-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

package.list <- c("dplyr","tidyverse","ggplot2","lemon","vegan","Rmisc","lubridate")

if(!all(package.list %in% installed.packages()[,"Package"])){
  install.packages(package.list[!(package.list %in% installed.packages()[,"Package"])])
}

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lemon)
library(vegan)
library(Rmisc)
library(lubridate)

#Subsectioning the bacteria data from the Taxonomic and Functional Annotations file####

# tax.func <- read.csv("CSV_files/TaxonomicAndFunctionalAnnotations.csv", sep = "\t")
# 
# tax.func <- separate(tax.func,col = full_classification,into = c("Domain","Supergroup","Division","Class","Order","Family","Genus","Species"), sep = ";", remove = FALSE, fill = "right", extra = "drop")
# 
# tax.func$Domain <- ifelse(substring(tax.func$Domain,1,1) == " ", substring(tax.func$Domain,2), tax.func$Domain)
# 
# Bacteria <- tax.func[tax.func$Domain == "Bacteria",]
# 
# bacteria$SequenceID <- ifelse(substring(bacteria$transcript_name, nchar(bacteria$transcript_name)-2, nchar(bacteria$transcript_name)-2) == ".",
#                               bacteria$SequenceID <- substring(bacteria$transcript_name,1,nchar(bacteria$transcript_name)-3),
#                               ifelse(substring(bacteria$transcript_name, nchar(bacteria$transcript_name)-3, nchar(bacteria$transcript_name)-3) == ".",
#                                      bacteria$SequenceID <- substring(bacteria$transcript_name,1,nchar(bacteria$transcript_name)-4),
#                                      bacteria$SequenceID <- bacteria$SequenceID))
# 
# write.csv(bacteria,"CSV_files/Bacteria.subsection.TFA.csv", row.names = F)

#Using the sequence ID's from the bacteria subsection to subsection the numreads and the TPM files####

# Bacteria <- read.csv("CSV_files/bacteria.subsection.TFA.csv")
# 
# salmon.numread <- read.csv("CSV_files/salmon.merged.numreads.subset5.csv")
# filter <- salmon.numread$Name %in% bacteria$SequenceID
# 
# Bacteria.numread <- salmon.numread[filter,]
# write.csv(Bacteria.numread,"CSV_files/Bacteria.subsection.numreads.csv",row.names = F)
# 
# salmon.TPM <- read.csv("CSV_files/salmon.merged.TPM.subset5.csv")
# 
# Bacteria.TPM <- salmon.TPM[filter,]
# write.csv(Bacteria.TPM, "CSV_files/Bacteria.subsection.TPM.csv",row.names = F)

#Reading the Bacteria numread and TPM subsectioned files.####

met.dat1 <- read.csv("CSV_files/dielRNA_eukrythmic.tsv", sep = "\t")
met.dat2 <- read.csv("sample_metadata.csv") %>% 
  mutate(Sample_ID = paste("HM",Sample_ID,sep = ""))

names(met.dat2)[names(met.dat2) == "Sample_ID"] <- "SampleID"

meta.data <- merge(met.dat1,met.dat2,by = "SampleID") %>% 
  mutate(datetime = ymd(substring(lubri,1,10))+hms(substring(lubri,12,19)))

#Raw read
Bacteria.numread <- read.csv("CSV_files/Bacteria.subsection.numreads.csv")

#Transcripts per million
Bacteria.TPM <- read.csv("CSV_files/Bacteria.subsection.TPM.csv")

# Bacteria.TFA <- read.csv("CSV_files/bacteria.subsection.TFA.csv")
# #Filtering out the sequences present in the Taxonomy and functional annotations data, but not in the numread/TPM
# filter <- Bacteria.TFA$SequenceID %in% Bacteria.numread$Name
# 
# Bacteria.TFA <- Bacteria.TFA[filter,]
```

Filter for kegg.ko then add the rest afterwards. Done, and it worked

```{r}
# filter <- Bacteria.TFA$KEGG_ko != "-"
# 
# Bacteria.KEGG <- Bacteria.TFA[filter,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# Bacteria.noKEGG <- Bacteria.TFA[!filter,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# filter2 <- Bacteria.noKEGG$SequenceID %in% Bacteria.KEGG$SequenceID
# 
# Bacteria.noKEGG <- Bacteria.noKEGG[!filter2,]
# 
# Bacteria.noRep <- rbind(Bacteria.KEGG,Bacteria.noKEGG)
# 
# write.csv(Bacteria.noRep,"CSV_files/Bacteria.TFA_NoRep.csv",row.names = F)
```

```{r}
Bacteria.TFA <- read.csv("CSV_files/Bacteria.TFA_NoRep.csv")
Bacteria.TFA$Class <- ifelse(substring(Bacteria.TFA$Class,nchar(Bacteria.TFA$Class)-7) == " (Class)",
                             substring(Bacteria.TFA$Class,1,nchar(Bacteria.TFA$Class)-8),
                             Bacteria.TFA$Class)

names(Bacteria.numread)[1] <- "SequenceID"

df.merged <- merge(Bacteria.numread,Bacteria.TFA,by = "SequenceID")
df.merged$Class <- substring(df.merged$Class,2)

df.merged$Class[is.na(df.merged$Class)] <- "Unclassified"


Class.vec <- unique(df.merged$Class)
n <- length(Class.vec)

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  Class.filter <- df.merged$Class == Class.vec[i]
  df.temp <- df.merged[Class.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,Class.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    
  }
}

df.merged2 <- df.merged[df.merged$Class != "Unclassified",]

top5.vec <- names(table(df.merged2$Class)[order(-table(df.merged2$Class))[1:5]])

top5.filter <- df.count$Class.vec %in% c(top5.vec,"Unclassified")

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day1_morning",
               "Day2_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","Class.vec"))

p1 <- ggplot(df.summ)+
  geom_bar(aes(fill = factor(Class.vec,
                             levels = c("Unclassified","Other",top5.vec)),
               y = Count,
               x = factor(Day, level = order.vec)),
           position = "stack", stat = "identity")+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "Class"))

p1
```
The 1, 2, and 3 are replicates, so they can be averaged and error bars added.

Make som plots with meta-data

make some plots with the cogs, split data and double count.

Try to look at the KEGG data
```{r}
Bacteria.TFA <- read.csv("CSV_files/Bacteria.TFA_NoRep.csv")
Bacteria.TFA$Class <- ifelse(substring(Bacteria.TFA$Class,nchar(Bacteria.TFA$Class)-7) == " (Class)",
                             substring(Bacteria.TFA$Class,1,nchar(Bacteria.TFA$Class)-8),
                             Bacteria.TFA$Class)

names(Bacteria.numread)[1] <- "SequenceID"

df.merged <- merge(Bacteria.numread,Bacteria.TFA,by = "SequenceID")
df.merged$Class <- substring(df.merged$Class,2)

df.merged$Class[is.na(df.merged$Class)] <- "Unclassified"


Class.vec <- unique(df.merged$Class)
n <- length(Class.vec)

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  Class.filter <- df.merged$Class == Class.vec[i]
  df.temp <- df.merged[Class.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,Class.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    
  }
}

df.merged2 <- df.merged[df.merged$Class != "Unclassified",]

top5.vec <- names(table(df.merged2$Class)[order(-table(df.merged2$Class))[1:7]])

top5.filter <- df.count$Class.vec %in% c(top5.vec,"Unclassified")

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_morning",
               "Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening",
               "Day2_night")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","Class.vec"))

Day.Time <- meta.data[,c("AssemblyGroup","datetime")]
names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"

dfOut2 <- merge(df.summ,Day.Time,by = "Day")

for(i in 1:length(unique(dfOut2$Class.vec))){
  filter <- dfOut2$Class.vec == unique(dfOut2$Class.vec)[i]
  
  dfTemp <- dfOut2[filter,] %>% 
    mutate(norm.data = (Count-min(Count))/(max(Count)-min(Count)))
  
  if(i != 1){
    dfOut3 <- rbind(dfTemp,dfOut3)
  } else {
    dfOut3 <- dfTemp
  }
}

# p2 <- ggplot(data = dfOut3)+
#   geom_line(aes(x = datetime,
#                 y = norm.data,
#                 color = Class.vec))+
#   geom_point(aes(x = datetime,
#                 y = norm.data,
#                 color = Class.vec))+
#   scale_x_continuous(breaks = unique(meta.data$datetime),
#                      labels = unique(meta.data$AssemblyGroup))+
#   theme(axis.text.x = element_text(angle = 90,
#                                    vjust = 0.5,
#                                    hjust=1))
# 
# p2

p2 <- ggplot(data = dfOut2)+
  geom_line(aes(x = datetime,
                y = Count,
                color = Class.vec))+
  geom_point(aes(x = datetime,
                y = Count,
                color = Class.vec))+
  geom_errorbar(aes(x = datetime,
                    y = Count,
                    ymax = Count+sd,
                    ymin = Count-sd))+
  facet_wrap(facets = "Class.vec",
             nrow = 3,
             ncol = 3,
             scales = "free_y")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  labs(title = "Relative numreads per day",
       y = "numreads per class / total numreads per day",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1),
        legend.position = "none")

p2
```


```{r}
Class.vec <- unique(df.merged$Class)

for(j in 1:length(Class.vec)){
  if(j == 1){
    df.mean <- 0
  }
  for(i in 1:24){
    
    if(i == 1){
      vec <- rep(NA,24)
    }
    
    vec[i] <- mean(df.merged[df.merged$Class == "Actinobacteria",i+1])
  }
}


```


```{r Bacteria data}
Bacteria.TFA <- read.csv("CSV_files/Bacteria.TFA_NoRep.csv")

dfOut <- Bacteria.TFA

# Create a bar plot
ggplot(dfOut, aes(x = Class))+
  geom_bar()+
  scale_y_log10()+
  labs(title = "Class Distribution",
       x = "Class",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```


