---
title: "Clustered_heatmap"
author: "Andreas Norlin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())

package.list <- c("dplyr","tidyverse","ggplot2",
                  "lemon","vegan","Rmisc",
                  "lubridate","patchwork","stringi",
                  "RColorBrewer","pheatmap")

if(!all(package.list %in% installed.packages()[,"Package"])){
  install.packages(package.list[!(package.list %in% installed.packages()[,"Package"])])
}

bioc.packages <- c("phyloseq","DESeq2")

if(!all(bioc.packages %in% installed.packages()[,"Package"])){
  if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(bioc.packages[!(bioc.packages %in% installed.packages()[,"Package"])])
}

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lemon)
library(vegan)
library(Rmisc)
library(lubridate)
library(RColorBrewer)

library(phyloseq)
library(patchwork)
library(DESeq2)
library(stringi)

library(pheatmap)

load("CSV_files/Subsections.RData",verbose = TRUE)
```

```{r}

# Setting up and splitting kegg columns ####

for(i in 1:nrow(Euk.Sub)){
  if(i == 1){
    n_KEGG <- length(unlist(strsplit(Euk.Sub$KEGG_ko[i],",")))
  }
  m_KEGG <- length(unlist(strsplit(Euk.Sub$KEGG_ko[i],",")))
  
  if(m_KEGG > n_KEGG){
    n_KEGG <- m_KEGG
  }
}

KEGG_columns <- paste("KEGG",1:n_KEGG,sep = "")

Euk.Sub <- separate(Euk.Sub,col = KEGG_ko,into = KEGG_columns,
                      sep = ",", remove = FALSE, fill = "right", extra = "drop")

# Kegg Path lookup####

Euk_KO_paths <- read.csv("KO_pathway_Euk.csv")

vec <- unlist(lapply(Euk.Sub$KEGG1,function(x){ifelse(x == "-","",Euk_KO_paths$ko[Euk_KO_paths$K1 == x])}))

vec[vec == ""] <- "Unclassified"

for(i in 1:nrow(Euk.Sub)){
  if(i == 1){
    Ko_path <- rep(NA,nrow(Euk.Sub))
  }

  vec <- Euk.Sub$KEGG1[i]

  vec_paths <- Euk_KO_paths$ko[Euk_KO_paths$K1 == vec]

  if(vec == "-"){
    vec_paths <- ""
  }

  if(vec_paths == ""){
    for(j in 2:length(KEGG_columns)){
      if(j == 2){
        stop_vec <- TRUE
      }

      if(stop_vec){
        vec <- Euk.Sub[i,KEGG_columns[j]]

        if(is.na(vec)){
          stop_vec <- FALSE
          vec_paths <- ""
        } else {
          vec_paths <- Euk_KO_paths$ko[Euk_KO_paths$K1 == vec]
        }

        if(vec_paths != ""){
          stop_vec <- FALSE
        }
      }
    }


  }
  if(vec_paths == ""){
    vec_paths <- "Unclassified"
  }

  Ko_path[i] <- vec_paths
}

Euk.Sub$K1_path <- Ko_path
```

```{r test}
AssemblyGroups <- unique(meta.data$AssemblyGroup)

AssemblyGroup.means <- matrix(nrow = nrow(Euk.Sub),ncol = length(AssemblyGroups))

for(i in 1:length(AssemblyGroups)){
  vec.cols <- paste0(meta.data$SampleID[meta.data$AssemblyGroup == AssemblyGroups[i]],"_quant")
  filter <- names(Euk.Sub) %in% vec.cols
  AssemblyGroup.means[,i] <- apply(Euk.Sub[,filter],1,mean)
}

rownames(AssemblyGroup.means) <- Euk.Sub$SequenceID
colnames(AssemblyGroup.means) <- AssemblyGroups

df.merged <- cbind.data.frame(AssemblyGroup.means,
                              "Family" = Euk.Sub$Family,
                              "K1_path" = Euk.Sub$K1_path)

# Euk.Sub$Family <- unlist(lapply(Euk.Sub$Family,function(x){unlist(strsplit(x,split = "_"))[1]}))
# 
# sort(unique(Euk.Sub$Family))

AsGroup <- AssemblyGroups[8]
filter <- names(df.merged) %in% c(AsGroup,"Family","K1_path")

df.merged2 <- df.merged[!is.na(df.merged$Family),filter]

kegg.paths <- unique(df.merged2$K1_path)
# kegg.paths2 <- rownames(df.count)
# save(kegg.paths2,file = "kegg.paths2.RData")

# source("pathway_API.R")

Euk.Families <- unique(df.merged2$Family)

n <- length(kegg.paths)
m <- length(Euk.Families)

#------------------------------------------------------------------------------
for(i in 1:n){ #Looping through the paths to count the occurrences.
  
  kegg.filter <- df.merged2$K1_path == kegg.paths[i]
  df.temp <- df.merged2[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     # df.count <- data.frame(matrix(ncol = m, nrow = n))
     # colnames(df.count) <- Euk.Families
     # rownames(df.count) <- kegg.paths2 #unlist(lapply(kegg.paths,function(x){if(x != "Unclassified"){pathway_API(x)$name}else{"Unclassified"}}))
     
     df.count2 <- data.frame(matrix(ncol = m, nrow = n))
     colnames(df.count2) <- Euk.Families
     rownames(df.count2) <- kegg.paths
     
     
   }
    
    Family.filter <- df.temp$Family == Euk.Families[j]
    
    vec <- sum(df.temp[Family.filter,1])
    
    df.count[i,j] <- ifelse(vec != 0,log(vec),-6)
    df.count2[i,j] <- vec
    
  }
}

vec_rows <- order(apply(df.count2,1,mean),decreasing = TRUE)
vec_cols <- order(apply(df.count2,2,mean),decreasing = TRUE)

heat_plot <- pheatmap(t(df.count[vec_rows,vec_cols]),
                      cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
                      clustering_distance_cols = 'euclidean',
                      clustering_distance_rows = 'euclidean',
                      clustering_method = 'ward.D',
                      main = AsGroup,
                      fontsize_row = 7,
                      fontsize_col = 5)

# Save it -----------------------------------------------------------
name_vec <- paste0("Heatmaps/",AsGroup,".pdf")

pdf(name_vec, height = 25, width = 20)
heat_plot
dev.off()


```


```{r test}
## Get heatmap ===================================================
pheatmap(data)

# Clustering ===================================================
pheatmap(data, 
         cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
         clustering_distance_cols = 'euclidean',
         clustering_distance_rows = 'euclidean',
         clustering_method = 'ward.D')

```

```{r}
Euk.Sub <- Euk.Sub[!is.na(Euk.Sub$Family),]

Euk.Families <- unique(Euk.Sub$Family)

vec1 <- rep(NA,length(Euk.Families))
vec2 <- rep(NA,length(Euk.Families))

for(i in 1:length(Euk.Families)){
  vec1[i] <- mean(apply(Euk.Sub[Euk.Sub$Family == Euk.Families[i],2:25],2,sum))
  vec2[i] <- Euk.Families[i]
}

dfOut <- cbind.data.frame(vec1,vec2)
```


```{r test}
AssemblyGroups <- unique(meta.data$AssemblyGroup)

AssemblyGroup.means <- matrix(nrow = nrow(Euk.Sub),ncol = length(AssemblyGroups))

for(i in 1:length(AssemblyGroups)){
  vec.cols <- paste0(meta.data$SampleID[meta.data$AssemblyGroup == AssemblyGroups[i]],"_quant")
  filter <- names(Euk.Sub) %in% vec.cols
  AssemblyGroup.means[,i] <- apply(Euk.Sub[,filter],1,mean)
}

rownames(AssemblyGroup.means) <- Euk.Sub$SequenceID
colnames(AssemblyGroup.means) <- AssemblyGroups

df.merged <- cbind.data.frame(AssemblyGroup.means,
                              "Family" = Euk.Sub$Family,
                              "K1_path" = Euk.Sub$K1_path)

df.merged <- df.merged[!is.na(df.merged$Family),]

kegg.paths <- unique(df.merged$K1_path)
Euk.Families <- unique(df.merged$Family)

n <- length(Euk.Families)
# n <- length(kegg.paths)
m <- length(AssemblyGroups)

#------------------------------------------------------------------------------
for(i in 1:n){ #Looping through the paths to count the occurrences.
  
  Family.filter <- df.merged$Family == Euk.Families[i]
  df.temp <- df.merged[Family.filter,]
  # kegg.filter <- df.merged$K1_path == kegg.paths[i]
  # df.temp <- df.merged[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     colnames(df.count) <- AssemblyGroups
     rownames(df.count) <- Euk.Families
     # rownames(df.count) <- kegg.paths
     
     
   }
    
    Day.filter <- names(df.temp) == AssemblyGroups[j]
    
    vec <- sum(df.temp[,Day.filter])
    
    df.count[i,j] <- log(vec+1)
    # df.count[i,j] <- sum(df.temp[,day.vec[j]])
    
  }
}

vec_rows <- order(apply(df.count,1,mean),decreasing = TRUE)
# vec_cols <- order(apply(df.count2,2,mean),decreasing = TRUE)

heat_plot <- pheatmap((df.count[vec_rows,]),
         cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
         clustering_distance_cols = 'euclidean',
         clustering_distance_rows = 'euclidean',
         clustering_method = 'ward.D',
                      fontsize_row = 7,
                      fontsize_col = 5)

name_vec <- paste0("Heatmaps/","All_pathways.pdf")

pdf(name_vec, height = 25, width = 20)
heat_plot
dev.off()


```










```{r}
Class_of_interest <- c("Bacillariophyta","Dinophyceae","Prymnesiophyceae","Cryptophyceae")

df.merged <- Euk.Sub[Euk.Sub$Class %in% Class_of_interest,]



for(i in 1:length(Class_of_interest)){
  
  filter <- df.merged$Class %in% c(Class_of_interest[-i],"Unclassified")
  
  df.Temp <- df.merged[!filter,]
  
  kegg.vec <- unique(df.Temp$K1_path)
  
  for(j in 1:length(kegg.vec)){
    if(j == 1){
      vec <- rep(NA,length(kegg.vec))
    }
    
    vec[j] <- sum(apply(df.Temp[df.Temp$K1_path == kegg.vec[j],2:25],1,mean))
    
    if(j == length(kegg.vec)){
      top10 <- kegg.vec[order(vec,decreasing = TRUE)[1:10]]
    }
  }
  
  if(i == 1){
    df_genes <- cbind(top10,
                      Class_of_interest[i],
                      paste0(top10,"_",Class_of_interest[i]))
    
  } else{
    df_genes <- rbind(df_genes,
                      cbind(top10,
                            Class_of_interest[i],
                            paste0(top10,"_",Class_of_interest[i])))
    
  }
}

top10_all <- unique(df_genes[,1])

# Pathway API -----------------------------------------------------------------
source("pathway_API.R")

paths <- unlist(lapply(top10_all,function(x){if(x != "Unclassified"){pathway_API(x)$name}else{"Unclassified"}}))

df_genes <- cbind(df_genes,
                  unlist(lapply(df_genes[,1], function(x){paths[top10_all == x]})))

names(df_genes) <- c("Pathway","Class","Identifier","Path")

# Start Counting

filter <- paste(df.merged$K1_path,df.merged$Class,sep = "_") %in% df_genes[,3]

df.merged <- df.merged[filter,]

n <- nrow(df_genes)
sample_vec <- paste0(meta.data$SampleID,"_quant")

m <- length(sample_vec)

for(i in 1:n){
  filter <- paste(df.merged$K1_path,df.merged$Class,sep = "_") == df_genes[i,3]
  
  df.Temp <- df.merged[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      
      rownames(df.count) <- df_genes[,3]
      colnames(df.count) <- meta.data$SampleName
    }
    
    vec <- sum(df.Temp[,names(df.Temp) == sample_vec[j]])
    
    df.count[i,j] <- log(vec+1)
  }
}

# Heatmap ---------------------------------------------------------------------

Pathway_cols <- c("#1B9E77","#D95F02","#7570B3","#E7298A",
                  "#66A61E","#E6AB02","#A6761D","#7FC97F",
                  "#BEAED4","#FDC086","#FFFF99","#386CB0",
                  "#F0027F","#BF5B17")
names(Pathway_cols) <- paths

Class_cols <- c('#f0b08f','#60555f','#9fd6e6','#63a375')
names(Class_cols) <- Class_of_interest

Count_cols <- list("Pathway" = Pathway_cols,
                   "Class" = Class_cols,
                   "Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))

Class_df <- data.frame(df_genes[,c(4,2)])
names(Class_df) <- c("Pathway","Class")
rownames(Class_df) <- df_genes[,3]

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap((df.count),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_row = Class_df,
             annotation_names_row = T,
             annotation_col = MetaData_df,
             annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             )


# name_vec <- paste0("Heatmaps/","Top4Class_Top10Paths.pdf")
# pdf(name_vec, height = 10, width = 8)

# heat_plot
# dev.off()
```

```{r}
Class_of_interest <- c("Bacillariophyta","Dinophyceae","Prymnesiophyceae","Cryptophyceae")

df.merged <- Euk.Sub[Euk.Sub$Class %in% Class_of_interest,]
# df.merged$KEGG1[is.na(df.merged$KEGG1)] <- "Unclassified"

df.merged <- df.merged[df.merged$K1_path != "Unclassified",]
df.merged <- df.merged[df.merged$KEGG1 != "-",]

n_keggs <- 5

for(i in 1:length(Class_of_interest)){
  
  filter <- df.merged$Class %in% Class_of_interest[i]
  
  df.Temp <- df.merged[filter,]
  
  kegg.vec <- unique(df.Temp$K1_path)
  
  for(j in 1:length(kegg.vec)){
    if(j == 1){
      vec <- rep(NA,length(kegg.vec))
    }
    
    vec[j] <- sum(apply(df.Temp[df.Temp$K1_path == kegg.vec[j],2:25],1,mean))
    
    if(j == length(kegg.vec)){
      top10 <- kegg.vec[order(vec,decreasing = TRUE)[1:10]]
      
      for(k in 1:length(top10)){
        filter <- df.Temp$K1_path == top10[k]
        
        df.Temp2 <- df.Temp[filter,]
        
        ko.vec <- unique(df.Temp2$KEGG1)
        
        for(l in 1:length(ko.vec)){
          if(l == 1){
            vec2 <- rep(NA,length(ko.vec))
          }
          
          vec2[l] <- sum(apply(df.Temp2[df.Temp2$KEGG1 == ko.vec[l],2:25],1,mean))
          
          if(l == length(ko.vec)){
            
            if(length(ko.vec) < n_keggs){
              top5_ko <- ko.vec[order(vec2,decreasing = TRUE)]
            }else{
              top5_ko <- ko.vec[order(vec2,decreasing = TRUE)[1:n_keggs]]
            }
            
          }
        }
        
        if(k == 1){
          top5ko_paths <- cbind(top5_ko,
                                top10[k])
        }else{
          top5ko_paths <- rbind(top5ko_paths,
                                cbind(top5_ko,
                                top10[k]))
        }
        
      }
    }
  }
  
  if(i == 1){
    df_genes <- cbind(top5ko_paths,
                      Class_of_interest[i],
                      paste0(top5ko_paths[,1],"_",Class_of_interest[i]))
    
  } else{
    df_genes <- rbind(df_genes,
                      cbind(top5ko_paths,
                            Class_of_interest[i],
                            paste0(top5ko_paths[,1],"_",Class_of_interest[i])))
    
  }
}

top10_all <- unique(df_genes[,2])

# Pathway API -----------------------------------------------------------------
source("pathway_API.R")

paths <- unlist(lapply(top10_all,function(x){if(x != "Unclassified"){pathway_API(x)$name}else{"Unclassified"}}))

df_genes <- cbind(df_genes,
                  unlist(lapply(df_genes[,2], function(x){paths[top10_all == x]})))

colnames(df_genes) <- c("ko","Pathway","Class","Identifier","Path")

# Start Counting

filter <- paste(df.merged$KEGG1,df.merged$Class,sep = "_") %in% df_genes[,4]

df.merged <- df.merged[filter,]

n <- nrow(df_genes)
sample_vec <- paste0(meta.data$SampleID,"_quant")

m <- length(sample_vec)

for(i in 1:n){
  filter <- paste(df.merged$KEGG1,df.merged$Class,sep = "_") == df_genes[i,4]
  
  df.Temp <- df.merged[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      
      rownames(df.count) <- df_genes[,4]
      colnames(df.count) <- meta.data$SampleName
    }
    
    vec <- df.Temp[,names(df.Temp) == sample_vec[j]]
    
    # df.count[i,j] <- log(vec)
    df.count[i,j] <- vec
  }
}

# Heatmap ---------------------------------------------------------------------

Pathway_cols <- c("#1B9E77","#D95F02","#7570B3","#E7298A",
                  "#66A61E","#E6AB02","#A6761D","#7FC97F",
                  "#BEAED4","#FDC086","#FFFF99","#386CB0",
                  "#F0027F","#BF5B17")
names(Pathway_cols) <- paths
# names(Pathway_cols) <- top10_all

Class_cols <- c('#f0b08f','#60555f','#9fd6e6','#63a375')
names(Class_cols) <- Class_of_interest

Count_cols <- list("Pathway" = Pathway_cols,
                   "Class" = Class_cols,
                   "Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))

Class_df <- data.frame(df_genes[,c(5,3)])
names(Class_df) <- c("Pathway","Class")
rownames(Class_df) <- df_genes[,4]

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap(cor(t(df.count)),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_col = Class_df,
             annotation_names_row = T,
             annotation_row = Class_df,
             annotation_names_col = T,
             # annotation_row = MetaData_df,
             # annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             cutree_rows = 4,cutree_cols = 4
             )


# name_vec <- paste0("Heatmaps/","Top4Class_Top5KO_top10Paths.pdf")
# pdf(name_vec, height = 8, width = 12)

name_vec <- paste0("Heatmaps/","Cor_Top4Class_Top5KO_top10Paths.pdf")
pdf(name_vec, height = 12, width = 14)

heat_plot
dev.off()
```

```{r}
load("par_paths.RData",verbose = T)

df.merged <- Euk.Sub

df.merged <- df.merged[df.merged$K1_path %in% par_paths,]

# Pathway API -----------------------------------------------------------------
source("pathway_API.R")

paths <- unlist(lapply(par_paths,function(x){if(x != "Unclassified"){pathway_API(x)$name}else{"Unclassified"}}))

par_paths <- cbind(par_paths,
                  unlist(lapply(par_paths, function(x){paths[par_paths == x]})))

names(par_paths) <- c("Pathway","name")

# Start Counting

n <- nrow(par_paths)
sample_vec <- paste0(meta.data$SampleID,"_quant")

m <- length(sample_vec)

for(i in 1:n){
  filter <- df.merged$K1_path == par_paths[i]
  
  df.Temp <- df.merged[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      
      rownames(df.count) <- par_paths[,2]
      colnames(df.count) <- meta.data$SampleName
    }
    
    vec <- sum(df.Temp[,names(df.Temp) == sample_vec[j]])
    
    df.count[i,j] <- log(vec+1)
  }
}

# Heatmap ---------------------------------------------------------------------




Count_cols <- list("Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))



MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap((df.count),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             # annotation_row = Class_df,
             # annotation_names_row = T,
             annotation_col = MetaData_df,
             annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = T, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             main = "Paths linearly correlated with par")


name_vec <- paste0("Heatmaps/","Par_paths_genes.pdf")

pdf(name_vec, height = 12, width = 8)
heat_plot
dev.off()
```

```{r}
# Setting up and splitting kegg columns ####

for(i in 1:nrow(Bact.Sub)){
  if(i == 1){
    n_KEGG <- length(unlist(strsplit(Bact.Sub$KEGG_ko[i],",")))
  }
  m_KEGG <- length(unlist(strsplit(Bact.Sub$KEGG_ko[i],",")))
  
  if(m_KEGG > n_KEGG){
    n_KEGG <- m_KEGG
  }
}

KEGG_columns <- paste("KEGG",1:n_KEGG,sep = "")

Bact.Sub <- separate(Bact.Sub,col = KEGG_ko,into = KEGG_columns,
                      sep = ",", remove = FALSE, fill = "right", extra = "drop")

ko_list <- unique(unlist(c(Bact.Sub[,grepl(pattern = "KEGG",names(Bact.Sub))][,-1])))
ko_list[is.na(ko_list)] <- "Unclassified"
ko_list[ko_list == "-"] <- "Unclassified"

source("pathway_API.R")

kegg_API <- function(kegg,First_path = TRUE){
  pathway <- system(paste0("curl https://rest.kegg.jp/link/pathway/", kegg), intern=TRUE)
  path_idx <- grep(paste0(kegg,"\tpath:ko"),pathway)

  ifelse(isEmpty(path_idx),
         "-",
         stri_sub(pathway[ifelse(First_path,min(path_idx),max(path_idx))], 16))
}

# for(i in 1:length(ko_list)){
#   if(i == 1){
#     paths <- matrix(NA,nrow = length(ko_list),ncol = 2)
#     colnames(paths) <- c("Path","K_number")
#     start_time <- Sys.time()
#   }
#   vec <- ko_list[i]
#   
#   paths[i,1] <- ifelse(vec != "Unclassified",kegg_API(vec,F),"Unclassified")
#   paths[i,2] <- vec
#   
#   if(i%%100 == 0){
#     
#     time_passed <- difftime(Sys.time(),start_time,units = "mins")
#     if(time_passed < 60){
#       print(paste("ko",i,"in the list.",round(time_passed,2),"minutes has passed"))
#     } else {
#       print(paste("ko",i,"in the list.",round(time_passed/60,2),"hours has passed"))
#     }
#   }
# }

# Setting up and splitting kegg columns ####

for(i in 1:nrow(Bact.Sub)){
  if(i == 1){
    n_KEGG <- length(unlist(strsplit(Bact.Sub$KEGG_ko[i],",")))
  }
  m_KEGG <- length(unlist(strsplit(Bact.Sub$KEGG_ko[i],",")))
  
  if(m_KEGG > n_KEGG){
    n_KEGG <- m_KEGG
  }
}

KEGG_columns <- paste("KEGG",1:n_KEGG,sep = "")

Bact.Sub <- separate(Bact.Sub,col = KEGG_ko,into = KEGG_columns,
                      sep = ",", remove = FALSE, fill = "right", extra = "drop")

load("KO_paths_Bact.RData")

Bact.Sub$K1_path <- unlist(lapply(Bact.Sub$KEGG1,function(x){ifelse(x != "-",paths[paths[,2] == x,1],"-")}))

```


```{r}
# Bact.Sub$KEGG1[Bact.Sub$KEGG1 == "-"] <- "Unclassified"
Bact.Sub <- Bact.Sub[Bact.Sub$KEGG1 != "-",]

kegg.vec <- unique(Bact.Sub$KEGG1)
n <- length(kegg.vec)

sample.vec <- paste0(meta.data$SampleID,"_quant")
m <- length(sample.vec)

for(i in 1:n){
  filter <- Bact.Sub$KEGG1 == kegg.vec[i]
  
  df.temp <- Bact.Sub[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      colnames(df.count) <- meta.data$SampleName
      rownames(df.count) <- kegg.vec
    }
    
    vec <- sum(df.temp[,names(df.temp) == sample.vec[j]])
    
    # df.count[i,j] <- ifelse(vec != 0,log(vec),-7.5)
    df.count[i,j] <- vec
    
  }
}



Count_cols <- list("Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))


paths <- paths[-3,]

paths_df <- data.frame(paths[paths[,2] %in% kegg.vec,1])
rownames(paths_df) <- paths[paths[,2] %in% kegg.vec,2]

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

cor_df.count <- cor(t(df.count[1:200,]))

heat_plot <- pheatmap(cor_df.count,
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_row = paths_df,
             annotation_names_row = F,
             annotation_col = paths_df,
             annotation_names_col = F,
             # annotation_col = MetaData_df,
             # annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             cutree_rows = 4,cutree_cols = 4
             )

# name_vec <- paste0("Heatmaps/","cor_Bact_all_keggs.pdf")
# 
# pdf(name_vec, height = 10, width = 8)
# heat_plot
# dev.off()

```


```{r}
#Euk.Sub$KEGG1[Euk.Sub$KEGG1 == "-"] <- "Unclassified"

Euk.Sub <- Euk.Sub[!(Euk.Sub$KEGG1 == "-"),]

kegg.vec <- unique(Euk.Sub$KEGG1)
n <- length(kegg.vec)

sample.vec <- paste0(meta.data$SampleID,"_quant")
m <- length(sample.vec)

for(i in 1:n){
  filter <- Euk.Sub$KEGG1 == kegg.vec[i]
  
  df.temp <- Euk.Sub[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      colnames(df.count) <- meta.data$SampleName
      rownames(df.count) <- kegg.vec
    }
    
    vec <- sum(df.temp[,names(df.temp) == sample.vec[j]])
    
    df.count[i,j] <- log(vec+1)
    
  }
}



Count_cols <- list("Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))


paths_df <- rbind(Euk_KO_paths[Euk_KO_paths$K1 %in% kegg.vec,])
rowname_vec <- paths_df$K1

paths_df <- data.frame(paths_df[,2])
rownames(paths_df) <- rowname_vec

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap((df.count),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_row = paths_df,
             annotation_names_row = F,
             annotation_col = MetaData_df,
             annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             )

name_vec <- paste0("Heatmaps/","Euk_all_keggs.pdf")

pdf(name_vec, height = 10, width = 8)
heat_plot
dev.off()

```

```{r}
Bact.Sub <- Bact.Sub[Bact.Sub$K1_path != "Unclassified",]

kegg.vec <- unique(Bact.Sub$K1_path)
n <- length(kegg.vec)

sample.vec <- paste0(meta.data$SampleID,"_quant")
m <- length(sample.vec)

for(i in 1:n){
  filter <- Bact.Sub$K1_path == kegg.vec[i]
  
  df.temp <- Bact.Sub[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      colnames(df.count) <- meta.data$SampleName
      rownames(df.count) <- kegg.vec
    }
    
    vec <- sum(df.temp[,names(df.temp) == sample.vec[j]])
    
    df.count[i,j] <- vec
    
  }
}



Count_cols <- list("Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))


# paths <- paths[-3,]
# 
# paths_df <- data.frame(paths[paths[,2] %in% kegg.vec,1])
# rownames(paths_df) <- paths[paths[,2] %in% kegg.vec,2]

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap(cor(t(df.count)),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             # annotation_row = paths_df,
             # annotation_names_row = F,
             # annotation_col = MetaData_df,
             # annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             )

# name_vec <- paste0("Heatmaps/","Cor_Bact_all_paths.pdf")
# 
# pdf(name_vec, height = 10, width = 8)
# heat_plot
# dev.off()

```

```{r}
Order_of_interest <- c("Alteromonadales","Oceanospirillales","Sphingomonadales","Cellvibrionales")
# Genus_of_interest <- c("Paraglaciecola","Colwellia")

# Order_of_interest <- c("Gammaproteobacteria","Alphaproteobacteria","Flavobacteriia","Actinobacteria (Class)","Oscillatoriophycideae",
#                        "Zetaproteobacteria","Deltaproteobacteria","Clostridia","Betaproteobacteria","Bacteroidia",
#                        "Cytophagia","Opitutae","Sphingobacteriia","Epsilonproteobacteria","Chlorobia",
#                        "Deinococci","Bacilli","Cyanophyceae","Spirochaetia","Actinobacteria",
#                        "Calditrichae","Bacillales (Class)","Deferribacteres (Class)","Aquificae (Class)","Thermotogae (Class)",
#                        "Fusobacteriia","Thermodesulfobacteria (Class)","Aquificae","Anaerolineae","Nitriliruptoria",
#                        "Phycisphaerae","Mollicutes","Oligoflexia","Erysipelotrichia","Rubrobacteria",
#                        "Synergistia")

df.merged <- Bact.Sub

sample.vec <- paste0(meta.data$SampleID,"_quant")

df.merged <- Bact.Sub[Bact.Sub$Order %in% Order_of_interest,]
# df.merged$KEGG1[is.na(df.merged$KEGG1)] <- "Unclassified"

df.merged <- df.merged[df.merged$K1_path != "-",]
df.merged <- df.merged[df.merged$KEGG1 != "-",]

n_keggs <- 5

for(i in 1:length(Order_of_interest)){
  
  filter <- df.merged$Order %in% Order_of_interest[i]
  
  df.Temp <- df.merged[filter,]
  
  kegg.vec <- unique(df.Temp$K1_path)
  
  for(j in 1:length(kegg.vec)){
    if(j == 1){
      vec <- rep(NA,length(kegg.vec))
    }
    
    vec[j] <- sum(apply(df.Temp[df.Temp$K1_path == kegg.vec[j],2:25],1,mean))
    
    if(j == length(kegg.vec)){
      if(length(kegg.vec) < 10){
        top10 <- kegg.vec[order(vec,decreasing = TRUE)]
      } else {
        top10 <- kegg.vec[order(vec,decreasing = TRUE)[1:10]]
      }
      
      for(k in 1:length(top10)){
        filter <- df.Temp$K1_path == top10[k]
        
        df.Temp2 <- df.Temp[filter,]
        
        ko.vec <- unique(df.Temp2$KEGG1)
        
        for(l in 1:length(ko.vec)){
          if(l == 1){
            vec2 <- rep(NA,length(ko.vec))
          }
          
          vec2[l] <- sum(apply(df.Temp2[df.Temp2$KEGG1 == ko.vec[l],2:25],1,mean))
          
          if(l == length(ko.vec)){
            
            if(length(ko.vec) < n_keggs){
              top5_ko <- ko.vec[order(vec2,decreasing = TRUE)]
            }else{
              top5_ko <- ko.vec[order(vec2,decreasing = TRUE)[1:n_keggs]]
            }
            
          }
        }
        
        if(k == 1){
          top5ko_paths <- cbind(top5_ko,
                                top10[k])
        }else{
          top5ko_paths <- rbind(top5ko_paths,
                                cbind(top5_ko,
                                top10[k]))
        }
        
      }
    }
  }
  
  if(i == 1){
    df_genes <- cbind(top5ko_paths,
                      Order_of_interest[i],
                      paste0(top5ko_paths[,1],"_",Order_of_interest[i]))
    
  } else{
    df_genes <- rbind(df_genes,
                      cbind(top5ko_paths,
                            Order_of_interest[i],
                            paste0(top5ko_paths[,1],"_",Order_of_interest[i])))
    
  }
}

top10_all <- unique(df_genes[,2])

# Pathway API -----------------------------------------------------------------
source("pathway_API.R")

paths <- unlist(lapply(top10_all,function(x){if(x != "Unclassified"){pathway_API(x)$name}else{"Unclassified"}}))

df_genes <- cbind(df_genes,
                  unlist(lapply(df_genes[,2], function(x){paths[top10_all == x]})))

names(df_genes) <- c("ko","Pathway","Order","Identifier","Path")

# Start Counting

filter <- paste(df.merged$KEGG1,df.merged$Order,sep = "_") %in% df_genes[,4]

df.merged <- df.merged[filter,]

n <- nrow(df_genes)
sample_vec <- paste0(meta.data$SampleID,"_quant")

m <- length(sample_vec)

for(i in 1:n){
  filter <- paste(df.merged$KEGG1,df.merged$Order,sep = "_") == df_genes[i,4]
  
  df.Temp <- df.merged[filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df.count <- matrix(NA,nrow = n,ncol = m)
      
      rownames(df.count) <- df_genes[,4]
      colnames(df.count) <- meta.data$SampleName
    }
    
    vec <- sum(df.Temp[,names(df.Temp) == sample_vec[j]])
    
    df.count[i,j] <- log(vec+.01)
    # df.count[i,j] <- sum(df.Temp[,names(df.Temp) == sample_vec[j]])
  }
}

# Heatmap ---------------------------------------------------------------------

Pathway_cols <- c("#1B9E77","#D95F02","#7570B3","#E7298A",
                  "#66A61E","#E6AB02","#A6761D","#7FC97F",
                  "#BEAED4","#FDC086","#FFFF99","#386CB0",
                  "#F0027F","#BF5B17","#60555f","#B7E1DD",
                  "blueviolet","darkblue")
# names(Pathway_cols) <- paths
names(Pathway_cols) <- top10_all

Order_cols <- c('#f0b08f','#60555f','#9fd6e6','#63a375')
names(Order_cols) <- Order_of_interest

Count_cols <- list("Pathway" = Pathway_cols,
                   "Order" = Order_cols,
                   "Day" = c("Day1" = "darkgreen",
                             "Day2" = "blueviolet"),
                   "Time.Of.Day" = c("afternoon" = "#F7F4B7",
                                     "night" = "darkblue",
                                     "morning" = "#B7E1DD",
                                     "evening" = "orange"))

Order_df <- data.frame(df_genes[,c(2,3)])
names(Order_df) <- c("Pathway","Order")
rownames(Order_df) <- df_genes[,4]

MetaData_df <- data.frame(meta.data[,c(4,5)])
names(MetaData_df) <- c("Day","Time.Of.Day")
rownames(MetaData_df) <- meta.data$SampleName

heat_plot <- pheatmap((t(df.count)),
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_col = Order_df,
             annotation_names_row = T,
             # annotation_row = Order_df,
             # annotation_names_col = T,
             annotation_row = MetaData_df,
             annotation_names_col = T,
             annotation_colors = Count_cols,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             cutree_rows = 2,cutree_cols = 4
             )


name_vec <- paste0("Heatmaps/","Bact_Top4Class_Top5KO_top10Paths.pdf")
pdf(name_vec, height = 8, width = 12)

# name_vec <- paste0("Heatmaps/","Cor_Bact_Top4Class_Top5KO_top10Paths.pdf")
# pdf(name_vec, height = 12, width = 12)

heat_plot
dev.off()

```


```{r}
cor_df <- cor(t(df.count),t(df.count2))

names(Order_df) <- c("Pathway2","Order")

Count_cols3 <- list("Pathway" = Count_cols2$Pathway,
                   #"Pathway2" = Count_cols$Pathway,
                   "Class" = Count_cols2$Class
                   #"Order" = Count_cols$Order
                   )

heat_plot <- pheatmap(cor_df,
             col = brewer.pal(10, 'RdYlGn'),
             cluster_rows = T, cluster_cols = T, # set to FALSE if you want to remove the dendograms
             clustering_distance_cols = 'euclidean',
             clustering_distance_rows = 'euclidean',
             clustering_method = 'ward.D',
             annotation_col = Class_df,
             annotation_names_col = T,
             # annotation_row = Order_df,
             # annotation_names_col = T,
             annotation_row = Order_df,
             annotation_names_row = T,
             annotation_colors = Count_cols3,
             show_rownames = F, show_colnames = F,
                          fontsize_row = 7,
                          fontsize_col = 5,
             cutree_rows = 6,cutree_cols = 5,
             main = "Bacteria Correlated with top4 Eukaryotes"
             )

name_vec <- paste0("Heatmaps/","Bact_vs_Top4Euks.pdf")
pdf(name_vec, height = 8, width = 12)

# name_vec <- paste0("Heatmaps/","Cor_Bact_Top4Class_Top5KO_top10Paths.pdf")
# pdf(name_vec, height = 12, width = 12)

heat_plot
dev.off()
```

