---
title: "Diel_Bacteria_sym"
author: "Andreas Norlin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())

package.list <- c("dplyr","tidyverse","ggplot2",
                  "lemon","vegan","Rmisc",
                  "lubridate","patchwork","stringi",
                  "RColorBrewer")

if(!all(package.list %in% installed.packages()[,"Package"])){
  install.packages(package.list[!(package.list %in% installed.packages()[,"Package"])])
}

bioc.packages <- c("phyloseq","DESeq2")

if(!all(bioc.packages %in% installed.packages()[,"Package"])){
  if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(bioc.packages[!(bioc.packages %in% installed.packages()[,"Package"])])
}

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lemon)
library(vegan)
library(Rmisc)
library(lubridate)
library(RColorBrewer)

library(phyloseq)
library(patchwork)
library(DESeq2)
library(stringi)

load("CSV_files/Subsections.RData",verbose = TRUE)
load("CSV_files/Full.merged.RData",verbose = TRUE)
```

```{r}
# #Loading the meta.data: meta.data1 is the Assmebly group and the sequencing ID (sample ID),
# #meta.data2 is the data about sampling time and site.
# 
# meta.data1 <- read.csv("CSV_files/dielRNA_eukrythmic.tsv", sep = "\t")
# meta.data2 <- read.csv("sample_metadata.csv") %>%
#   mutate(Sample_ID = paste("HM",Sample_ID,sep = ""))
# 
# names(meta.data2)[names(meta.data2) == "Sample_ID"] <- "SampleID"
# 
# #Combining meta.data1 and meta.data2 and making the lubri string a data + time saved in datetime
# meta.data <- merge(meta.data1,meta.data2,by = "SampleID") %>%
#   mutate(datetime = ymd(substring(lubri,1,10))+hms(substring(lubri,12,19)))
# 
# meta.data <- separate(meta.data, col = AssemblyGroup, into = c("Day.num","ToD"),sep = "_",remove = FALSE, fill = "right", extra = "drop")
# 
# # meta.data$lubri <- with_tz(mdy_hms(meta.data$datetime, tz = "UTC"),
# #                            tz = "America/Santiago")
# 
# COG_categories <- read.csv("COG_categories.csv",sep = ";")
# 
# Full.merged <- read.csv("CSV_files/Full.merged.csv")
# 
# par1 <- read.delim("NBP2113pguv.d342",  sep = " ", header =FALSE)
# par2<- read.delim("NBP2113pguv.d343",  sep = " ", header =FALSE)
# par3<- read.delim("NBP2113pguv.d344",  sep = " ", header =FALSE)
# 
# par = rbind(par1, par2, par3)[-1,c(1,2,3,10)]
# names(par) <- c("juliendatetime","date", "time", "par")
# 
# partime <- par %>%
#   separate(juliendatetime, c("yearday","hour", "min", "sec"), sep = ":" ) %>%
#   unite(utctime, hour, min, sec, sep=":")  %>%
#   mutate(utcdatetime = paste(date, utctime))
# 
# partime$lubri <- with_tz(mdy_hms(partime$utcdatetime, tz = "UTC"),
#                          tz = "America/Santiago")
# 
# for(i in 1:nrow(meta.data)){
# 
#   filter.above <- partime$lubri >= meta.data$datetime[i]
#   filter.below <- partime$lubri < meta.data$datetime[i]
# 
#   vec.above <- partime[partime$lubri == min(partime$lubri[filter.above]),]
#   vec.below <- partime[partime$lubri == max(partime$lubri[filter.below]),]
# 
#   meta.data$par[i] <- mean(vec.above$par,vec.below$par)
# 
# }
# 
# m <- 1
# time.int <- ms("05.00")
# for(i in 1:nrow(partime)){
#   if(i == 1){
#     vec <- NA
#     vec.slide <- NA
#     n <- 1
#   }
# 
#   test.vec <- partime$lubri[i] - partime$lubri[m]
# 
#   if(test.vec > time.int){
#     m <- i
# 
#     vec[n] <- i
# 
#     n <- n+1
#   }
# 
# }
# 
# partime <- partime[vec,]
# 
# #Creating subsections####
# 
# Prok.Sub <- Full.merged[Full.merged$Domain != "Eukaryota",]
# Euk.Sub <- Full.merged[Full.merged$Domain == "Eukaryota",]
# Bact.Sub <- Full.merged[Full.merged$Domain == "Bacteria",]
# 
# save(Bact.Sub,Prok.Sub,Euk.Sub,meta.data,partime,file = "CSV_files/Subsections.RData")
# save(Full.merged,meta.data,partime,file = "CSV_files/Full.merged.RData")
```


```{r Loading and cleaning the raw data}
# tax.func <- read.csv("CSV_files/TaxonomicAndFunctionalAnnotations.csv", sep = "\t")
# 
# #Splitting the column with full_classification into seperate columns
# tax.func <- separate(tax.func,
#                      col = full_classification,
#                      into = c("Domain","Supergroup","Division","Class","Order","Family","Genus","Species"),
#                      sep = "; ",
#                      remove = FALSE,
#                      fill = "right",
#                      extra = "drop")
# 
# tax.func <- tax.func[tax.func$Domain != "",]
# 
# #Cleaning up data by removing blank spaces at the beginning of entries in the newly separated columns.
# Class_hierarchy <- c("Domain","Supergroup","Division","Class","Order","Family","Genus","Species")
# 
# for(i in 1:length(Class_hierarchy)){
#   Col_filter <- names(tax.func) == Class_hierarchy[i]
# 
#   tax.func[,Col_filter] <- ifelse(substring(tax.func[,Col_filter],1,1) == " ",
#                                           substring(tax.func[,Col_filter],2),
#                                           tax.func[,Col_filter])
# }
# 
# #Removing the .p after sequence names, in order to remove duplicate sequences later.
# tax.func$SequenceID <- unlist(lapply(tax.func$SequenceID,
#                                       function(x){unlist(strsplit(x,split = ".",fixed = TRUE))[1]}))
# 
# salmon.TPM <- read.csv("CSV_files/salmon.merged.TPM.subset5.csv")
# filter <- salmon.TPM$Name %in% tax.func$SequenceID
# 
# Full.TPM <- salmon.TPM[filter,]
# 
# #Filtering out the sequences present in the Taxonomy and functional annotations data, but not in the TPM
# filter <- tax.func$SequenceID %in% Full.TPM$Name
# 
# tax.func <- tax.func[filter,]
# 
# #Seperates sequences with a KEGG from the sequences that don't
# filter <- tax.func$KEGG_ko != "-"
# 
# Full.KEGG <- tax.func[filter,]
# Full.noKEGG <- tax.func[!filter,]
# 
# #Creates a filter for the sequences that have KEGGs to seperate COGs and noCOGs
# filter1 <- Full.KEGG$COG_category == "-"
# 
# Full.KEGG.COG <- Full.KEGG[!filter1,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# Full.KEGG.noCOG <- Full.KEGG[filter1,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# #Removes sequences from noCOG that is present in COG
# filter2 <- Full.KEGG.noCOG$SequenceID %in% Full.KEGG.COG$SequenceID
# 
# Full.KEGG <- rbind(Full.KEGG.COG,Full.KEGG.noCOG[!filter2,])
# 
# #Creates a filter for the sequences that doesn't have KEGGs to seperate COGs and noCOGs
# filter1 <- Full.noKEGG$COG_category == "-"
# 
# Full.noKEGG.COG <- Full.noKEGG[!filter1,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# Full.noKEGG.noCOG <- Full.noKEGG[filter1,] %>%
#   distinct(SequenceID, .keep_all = TRUE)
# 
# #Removes sequences from noCOG that is present in COG
# filter2 <- Full.noKEGG.noCOG$SequenceID %in% Full.noKEGG.COG$SequenceID
# 
# Full.noKEGG <- rbind(Full.noKEGG.COG,Full.noKEGG.noCOG[!filter2,])
# 
# #Filtering Sequences in noKEGG that are present in KEGG
# filter3 <- Full.noKEGG$SequenceID %in% Full.KEGG$SequenceID
# 
# Full.noRep <- rbind(Full.KEGG,Full.noKEGG[!filter3,])
# 
# write.csv(Full.noRep,"CSV_files/tax.func_NoRep.csv",row.names = F)
# 
# names(Full.TPM)[1] <- "SequenceID"
# 
# df.merged <- merge(Full.TPM,Full.noRep,by = "SequenceID")
# 
# write.csv(df.merged,"CSV_files/Full.merged.csv",row.names = F)
```

```{r Cleaning categories}
# 
# Full.noRep$Class <- ifelse(substring(Full.noRep$Class,nchar(Full.noRep$Class)-7) == " (Class)",
#                            substring(Full.noRep$Class,1,nchar(Full.noRep$Class)-8),
#                            Full.noRep$Class) #Is this statement even needed?
# 
# for(i in 1:length(Class_hierarchy)){
#   Col_filter <- names(df.merged) == Class_hierarchy[i]
#   row_filter <- is.na(df.merged[,Col_filter])
# 
#   df.merged[row_filter,Col_filter] <- "Unclassified"
# }

```

```{r}
source("split_function.R")

# Setting up and splitting kegg columns ####

for(i in 1:nrow(Bact.Sub)){
  if(i == 1){
    n_KEGG <- length(unlist(split_function(Bact.Sub$KEGG_ko[i],",")))
  }
  m_KEGG <- length(unlist(split_function(Bact.Sub$KEGG_ko[i],",")))
  
  if(m_KEGG > n_KEGG){
    n_KEGG <- m_KEGG
  }
}

KEGG_columns <- paste("KEGG",1:n_KEGG,sep = "")

Bact.Sub <- separate(Bact.Sub,col = KEGG_ko,into = KEGG_columns,
                      sep = ",", remove = FALSE, fill = "right", extra = "drop")
```


```{r}
df.merged <- Bact.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"
kegg.vec <- unique(df.merged$KEGG1)

n <- length(kegg.vec)

# df.merged <- df.merged[df.merged$K1_path != "Unclassified",]

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
  df.temp <- df.merged[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,kegg.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    # df.count[i,j] <- sum(df.temp[,day.vec[j]])
    
  }
}

df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:15]]

top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
# top5.filter <- df.count$kegg.vec %in% c(top5.vec)

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day1_morning",
               "Day2_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","kegg.vec"))

Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
  distinct(AssemblyGroup, .keep_all = TRUE)

names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"

dfOut2 <- merge(df.summ,Day.Time,by = "Day")
# dfOut2_O.U <- dfOut2[(dfOut2$kegg.vec %in% c("Other","Unclassified")),]
# 
# dfOut2 <- dfOut2[!(dfOut2$kegg.vec %in% c("Other","Unclassified")),]

partime$norm.par <- partime$par / max(partime$par)

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- top5.vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut2)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut2))
    }
    
    if(dfOut2$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut2$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut2$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(top5.vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == top5.vec[i]]
    
    top5.vec[i] <- vec
  }
  
  dfOut2$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut2 <- dfOut2[!(dfOut2$kegg.vec %in% c("Unclassified","Other")),]

p1 <- ggplot(dfOut2)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",top5.vec)),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),brewer.pal(8,"Set2"),brewer.pal(9,"Set1")))+
  labs(title = "All Bacteria",
       y = "Fraction of TPM",
       x = "Time of sample",
       caption = "This is a caption")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none")

# scale <- max(partime$par)
# 
# p1 <- p1 +
#   geom_line(data = partime,
#             aes(x = lubri,
#                 y = norm.par,
#                 alpha = 0.5))+
#   scale_y_continuous(sec.axis = sec_axis(~.*scale, name = "Secondary Y-axis"))

p1

save_name <- "KO_plots/AllBact_topKO.png"
ggsave(save_name,width = 10,height = 5,dpi = 300)

```

```{r}
Order_of_interest <- c("Alteromonadales","Oceanospirillales","Sphingomonadales","Cellvibrionales")
Genus_of_interest <- c("Paraglaciecola","Colwellia")

df.merged <- Bact.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"
kegg.vec <- unique(df.merged$KEGG1)

n <- length(kegg.vec)

#Counting TPM for keggs for each order of interest####
df.merged_copy <- df.merged
df.merged_NoNA <- df.merged_copy[!is.na(df.merged_copy$Order),]

for(order_idx in Order_of_interest){
  
  order_filter <- df.merged_NoNA$Order == order_idx
  
  df.merged <- df.merged_NoNA[order_filter,]
  
  day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
  m <- length(day.vec)
  
  for(i in 1:n){ #Looping through the Classes to count the occurrences.
    
    kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
    df.temp <- df.merged[kegg.filter,]
    
    for(j in 1:m){ #Looping through the sampling time points.
      
     if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
       
       df.count <- data.frame(matrix(ncol = m, nrow = n))
       names(df.count) <- meta.data$SampleName
       
       df.count <- cbind(df.count,kegg.vec)
     }
      
      df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
      # df.count[i,j] <- sum(df.temp[,day.vec[j]])
      
    }
  }
  
  df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

  top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:5]]
  
  top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
  # top5.filter <- df.count$kegg.vec %in% c(top5.vec)
  
  df.top5 <- df.count[top5.filter,]
  df.other <- df.count[!top5.filter,]
  
  df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))
  
  order.vec <- c("Day1_afternoon",
                 "Day1_evening",
                 "Day1_night",
                 "Day1_morning",
                 "Day2_night",
                 "Day2_morning",
                 "Day2_afternoon",
                 "Day2_evening")
  
  dfOut <- pivot_longer(df.count2,
                        all_of(meta.data$SampleName),
                        names_to = "Day",
                        values_to = "Count") %>% 
    mutate(Count = as.numeric(Count))
  
  dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)
  
  df.summ <- summarySE(data = dfOut, "Count",
                       groupvars = c("Day","kegg.vec"))
  
  Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
    distinct(AssemblyGroup, .keep_all = TRUE)
  
  names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"
  
  dfOut2 <- merge(df.summ,Day.Time,by = "Day") %>% 
    mutate(Facet_name = order_idx)
  
  name_vec <- paste("dfOut2_",order_idx,sep = "")
  assign(name_vec,dfOut2,envir = globalenv())
  
  if(order_idx == Order_of_interest[1]){
    dfOut3 <- dfOut2
  }else{
    dfOut3 <- rbind.data.frame(dfOut3,dfOut2)
  }
}
#####

level_vec <- unique(dfOut3$kegg.vec)[!(unique(dfOut3$kegg.vec) %in% c("Unclassified","Other"))]

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- level_vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut3)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut3))
    }
    
    if(dfOut3$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut3$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut3$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(level_vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == level_vec[i]]
    
    level_vec[i] <- vec
  }
  
  dfOut3$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut3 <- dfOut3[!(dfOut3$kegg.vec %in% c("Unclassified","Other")),]

p3 <- ggplot(dfOut3)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",level_vec)
                             ),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1"),
                               brewer.pal(9,"Pastel1")))+
  facet_wrap(facets = "Facet_name",
             nrow = 2,
             ncol = 2,
             scales = "free_y")+
  labs(title = "Orders",
       y = "Fraction of TPM",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "Pathway"),
         alpha = "none",
         color = guide_legend(title = "Shape"))

p3

save_name <- "KO_plots/FourBact_topKO.png"
ggsave(save_name,width = 10,height = 6,dpi = 300)
```

```{r}
Order_of_interest <- c("Alteromonadales","Oceanospirillales","Sphingomonadales","Cellvibrionales")
Genus_of_interest <- c("Paraglaciecola","Colwellia")

df.merged <- Bact.Sub

# assigning pathways------------------------------------------------------------

Prok_KO_paths <- read.csv("KO_pathway.csv")

for(i in 1:nrow(Bact.Sub)){
  if(i == 1){
    Ko_path <- rep(NA,nrow(Bact.Sub))
  }

  vec <- Bact.Sub$KEGG1[i]

  vec_paths <- Prok_KO_paths$ko[Prok_KO_paths$K1 == vec]

  if(vec == "-"){
    vec_paths <- ""
  }

  if(vec_paths == ""){
    for(j in 2:length(KEGG_columns)){
      if(j == 2){
        stop_vec <- TRUE
      }

      if(stop_vec){
        vec <- Bact.Sub[i,KEGG_columns[j]]

        if(is.na(vec)){
          stop_vec <- FALSE
          vec_paths <- ""
        } else {
          vec_paths <- Prok_KO_paths$ko[Prok_KO_paths$K1 == vec]
        }

        if(vec_paths != ""){
          stop_vec <- FALSE
        }
      }
    }


  }
  if(vec_paths == ""){
    vec_paths <- "Unclassified"
  }

  Ko_path[i] <- vec_paths
}

Bact.Sub$K1_path <- Ko_path

# Counting TPM -----------------------------------------------------------------

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"

#Counting TPM for keggs for each order of interest####
df.merged_copy <- df.merged
df.merged_NoNA <- df.merged_copy[!is.na(df.merged_copy$Order),]

for(order_idx in Order_of_interest){
  
    order_filter <- df.merged_NoNA$Order == order_idx
    
    df.merged <- df.merged_NoNA[order_filter,]
    
    filter <- df.merged$K1_path == "ko01100"

    df.merged <- df.merged[filter,]
    
    kegg.vec <- unique(df.merged$KEGG1)
    n <- length(kegg.vec)
    
    day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
    m <- length(day.vec)
  
  for(i in 1:n){ #Looping through the Classes to count the occurrences.
      
    kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
    df.temp <- df.merged[kegg.filter,]
    
    for(j in 1:m){ #Looping through the sampling time points.
      
     if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
       
       df.count <- data.frame(matrix(ncol = m, nrow = n))
       names(df.count) <- meta.data$SampleName
       
       df.count <- cbind(df.count,kegg.vec)
     }
      
      df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
      # df.count[i,j] <- sum(df.temp[,day.vec[j]])
      
    }
  }
  
  top5.vec <- df.count$kegg.vec[order(apply(df.count[,-ncol(df.count)],1,sum),decreasing = TRUE)[1:7]]
  
  top5.filter <- df.count$kegg.vec %in% c(top5.vec)
    # top5.filter <- df.count$kegg.vec %in% c(top5.vec)
    
    df.top5 <- df.count[top5.filter,]
    df.other <- df.count[!top5.filter,]
    
    df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))
    
  order.vec <- c("Day1_afternoon",
                 "Day1_evening",
                 "Day1_night",
                 "Day1_morning",
                 "Day2_night",
                 "Day2_morning",
                 "Day2_afternoon",
                 "Day2_evening")
  
  dfOut <- pivot_longer(df.count2,
                        all_of(meta.data$SampleName),
                        names_to = "Day",
                        values_to = "Count") %>% 
    mutate(Count = as.numeric(Count))
  
  dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)
  
  df.summ <- summarySE(data = dfOut, "Count",
                       groupvars = c("Day","kegg.vec"))
  
  Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
    distinct(AssemblyGroup, .keep_all = TRUE)
  
  names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"
  
  dfOut2 <- merge(df.summ,Day.Time,by = "Day") %>% 
    mutate(Facet_name = order_idx)
  
  name_vec <- paste("dfOut2_",order_idx,sep = "")
  assign(name_vec,dfOut2,envir = globalenv())
  
  if(order_idx == Order_of_interest[1]){
    dfOut3 <- dfOut2
  }else{
    dfOut3 <- rbind.data.frame(dfOut3,dfOut2)
  }

}

level_vec <- unique(dfOut3$kegg.vec)[!(unique(dfOut3$kegg.vec) %in% c("Unclassified","Other"))]

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- level_vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut3)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut3))
    }
    
    if(dfOut3$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut3$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut3$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(level_vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == level_vec[i]]
    
    level_vec[i] <- vec
  }
  
  dfOut3$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

p4 <- ggplot(dfOut3)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",level_vec)
                             ),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1"),
                               brewer.pal(12,"Paired")))+
  facet_wrap(facets = "Facet_name",
             nrow = 2,
             ncol = 2,
             scales = "free_y")+
  labs(title = "Metabolic Pathway",
       y = "Fraction of TPM",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none",
         color = guide_legend(title = "Shape"))

p4

save_name <- paste("KO_plots/FourBact_MetabolicPathway.png",sep = "")
ggsave(save_name,width = 10,height = 6,dpi = 300)
```



```{r}
Order_of_interest <- c("Alteromonadales","Oceanospirillales","Sphingomonadales","Cellvibrionales")
Genus_of_interest <- c("Paraglaciecola","Colwellia")

df.merged <- Bact.Sub

# assigning pathways------------------------------------------------------------

Prok_KO_paths <- read.csv("KO_pathway.csv")

for(i in 1:nrow(Bact.Sub)){
  if(i == 1){
    Ko_path <- rep(NA,nrow(Bact.Sub))
  }

  vec <- Bact.Sub$KEGG1[i]

  vec_paths <- Prok_KO_paths$ko[Prok_KO_paths$K1 == vec]

  if(vec == "-"){
    vec_paths <- ""
  }

  if(vec_paths == ""){
    for(j in 2:length(KEGG_columns)){
      if(j == 2){
        stop_vec <- TRUE
      }

      if(stop_vec){
        vec <- Bact.Sub[i,KEGG_columns[j]]

        if(is.na(vec)){
          stop_vec <- FALSE
          vec_paths <- ""
        } else {
          vec_paths <- Prok_KO_paths$ko[Prok_KO_paths$K1 == vec]
        }

        if(vec_paths != ""){
          stop_vec <- FALSE
        }
      }
    }


  }
  if(vec_paths == ""){
    vec_paths <- "Unclassified"
  }

  Ko_path[i] <- vec_paths
}

Bact.Sub$K1_path <- Ko_path

# Counting TPM -----------------------------------------------------------------

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"

#Counting TPM for keggs for each order of interest####
df.merged_copy <- df.merged
df.merged_NoNA <- df.merged_copy[!is.na(df.merged_copy$Order),]

for(order_idx in Order_of_interest){
  
    order_filter <- df.merged_NoNA$Order == order_idx
    
    df.merged <- df.merged_NoNA[order_filter,]
    
    filter <- df.merged$K1_path == "ko03010"

    df.merged <- df.merged[filter,]
    
    kegg.vec <- unique(df.merged$KEGG1)
    n <- length(kegg.vec)
    
    day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
    m <- length(day.vec)
  
  for(i in 1:n){ #Looping through the Classes to count the occurrences.
      
    kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
    df.temp <- df.merged[kegg.filter,]
    
    for(j in 1:m){ #Looping through the sampling time points.
      
     if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
       
       df.count <- data.frame(matrix(ncol = m, nrow = n))
       names(df.count) <- meta.data$SampleName
       
       df.count <- cbind(df.count,kegg.vec)
     }
      
      df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
      # df.count[i,j] <- sum(df.temp[,day.vec[j]])
      
    }
  }
  
  top5.vec <- df.count$kegg.vec[order(apply(df.count[,-ncol(df.count)],1,sum),decreasing = TRUE)[1:5]]
  
  top5.filter <- df.count$kegg.vec %in% c(top5.vec)
    # top5.filter <- df.count$kegg.vec %in% c(top5.vec)
    
    df.top5 <- df.count[top5.filter,]
    df.other <- df.count[!top5.filter,]
    
    df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))
    
  order.vec <- c("Day1_afternoon",
                 "Day1_evening",
                 "Day1_night",
                 "Day1_morning",
                 "Day2_night",
                 "Day2_morning",
                 "Day2_afternoon",
                 "Day2_evening")
  
  dfOut <- pivot_longer(df.count2,
                        all_of(meta.data$SampleName),
                        names_to = "Day",
                        values_to = "Count") %>% 
    mutate(Count = as.numeric(Count))
  
  dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)
  
  df.summ <- summarySE(data = dfOut, "Count",
                       groupvars = c("Day","kegg.vec"))
  
  Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
    distinct(AssemblyGroup, .keep_all = TRUE)
  
  names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"
  
  dfOut2 <- merge(df.summ,Day.Time,by = "Day") %>% 
    mutate(Facet_name = order_idx)
  
  name_vec <- paste("dfOut2_",order_idx,sep = "")
  assign(name_vec,dfOut2,envir = globalenv())
  
  if(order_idx == Order_of_interest[1]){
    dfOut3 <- dfOut2
  }else{
    dfOut3 <- rbind.data.frame(dfOut3,dfOut2)
  }

}

level_vec <- unique(dfOut3$kegg.vec)[!(unique(dfOut3$kegg.vec) %in% c("Unclassified","Other"))]

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- level_vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut3)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut3))
    }
    
    if(dfOut3$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut3$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut3$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(level_vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == level_vec[i]]
    
    level_vec[i] <- vec
  }
  
  dfOut3$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

p4 <- ggplot(dfOut3)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",level_vec)
                             ),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1"),
                               brewer.pal(12,"Paired")))+
  facet_wrap(facets = "Facet_name",
             nrow = 2,
             ncol = 2,
             scales = "free_y")+
  labs(title = "Ribosome",
       y = "Fraction of TPM",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none",
         color = guide_legend(title = "Shape"))

p4

save_name <- paste("KO_plots/FourBact_Ribosome.png",sep = "")
ggsave(save_name,width = 10,height = 5,dpi = 300)
```

```{r}
Euk.Sub <- Full.merged[Full.merged$Domain == "Eukaryota",]

# source("split_function.R")

# Setting up and splitting kegg columns ####

for(i in 1:nrow(Euk.Sub)){
  if(i == 1){
    n_KEGG <- length(unlist(split_function(Euk.Sub$KEGG_ko[i],",")))
  }
  m_KEGG <- length(unlist(split_function(Euk.Sub$KEGG_ko[i],",")))
  
  if(m_KEGG > n_KEGG){
    n_KEGG <- m_KEGG
  }
}

KEGG_columns <- paste("KEGG",1:n_KEGG,sep = "")

Euk.Sub <- separate(Euk.Sub,col = KEGG_ko,into = KEGG_columns,
                      sep = ",", remove = FALSE, fill = "right", extra = "drop")
```

```{r}
df.merged <- Euk.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"
kegg.vec <- unique(df.merged$KEGG1)
n <- length(kegg.vec)

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
  df.temp <- df.merged[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,kegg.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    # df.count[i,j] <- sum(df.temp[,day.vec[j]])
    
  }
}

df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:15]]

top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
# top5.filter <- df.count$kegg.vec %in% c(top5.vec)

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day1_morning",
               "Day2_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","kegg.vec"))

Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
  distinct(AssemblyGroup, .keep_all = TRUE)

names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"

dfOut2 <- merge(df.summ,Day.Time,by = "Day")

partime$norm.par <- partime$par / max(partime$par)

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- top5.vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut2)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut2))
    }
    
    if(dfOut2$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut2$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut2$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(top5.vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == top5.vec[i]]
    
    top5.vec[i] <- vec
  }
  
  dfOut2$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut2 <- dfOut2[!(dfOut2$kegg.vec %in% c("Unclassified","Other")),]

p6 <- ggplot(dfOut2)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",top5.vec)),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1")))+
  labs(title = "All Eukaryotes",
       y = "Fraction of TPM",
       x = "Time of sample",
       caption = "This is a caption")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none")

p6

save_name <- "KO_plots/AllEuk_topKO.png"
ggsave(save_name,width = 10,height = 5,dpi = 300)
```


```{r}
Class_of_interest <- c("Bacillariophyta","Dinophyceae","Prymnesiophyceae","Cryptophyceae")
Order_of_interest <- c("Bacillariales","Cryptomonadales","Dinophysiales","Phaeocystales")
Genus_of_interest <- c("Paraglaciecola","Colwellia")

df.merged <- Euk.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"

#Counting TPM for keggs for each order of interest####
df.merged_copy <- df.merged
df.merged_NoNA <- df.merged_copy[!is.na(df.merged_copy$Order),]

for(order_idx in Order_of_interest){
  
  order_filter <- df.merged_NoNA$Order == order_idx
  
  df.merged <- df.merged_NoNA[order_filter,]
  
  kegg.vec <- unique(df.merged$KEGG1)

  n <- length(kegg.vec)
  
  day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
  m <- length(day.vec)
  
  for(i in 1:n){ #Looping through the Classes to count the occurrences.
    
    kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
    df.temp <- df.merged[kegg.filter,]
    
    for(j in 1:m){ #Looping through the sampling time points.
      
     if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
       
       df.count <- data.frame(matrix(ncol = m, nrow = n))
       names(df.count) <- meta.data$SampleName
       
       df.count <- cbind(df.count,kegg.vec)
     }
      
      df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
      # df.count[i,j] <- sum(df.temp[,day.vec[j]])
      
    }
  }
  
  df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

  top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:5]]
  
  top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
  # top5.filter <- df.count$kegg.vec %in% c(top5.vec)
  
  df.top5 <- df.count[top5.filter,]
  df.other <- df.count[!top5.filter,]
  
  df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))
  
  order.vec <- c("Day1_afternoon",
                 "Day1_evening",
                 "Day1_night",
                 "Day1_morning",
                 "Day2_night",
                 "Day2_morning",
                 "Day2_afternoon",
                 "Day2_evening")
  
  dfOut <- pivot_longer(df.count2,
                        all_of(meta.data$SampleName),
                        names_to = "Day",
                        values_to = "Count") %>% 
    mutate(Count = as.numeric(Count))
  
  dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)
  
  df.summ <- summarySE(data = dfOut, "Count",
                       groupvars = c("Day","kegg.vec"))
  
  Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
    distinct(AssemblyGroup, .keep_all = TRUE)
  
  names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"
  
  dfOut2 <- merge(df.summ,Day.Time,by = "Day") %>% 
    mutate(Facet_name = order_idx)
  
  name_vec <- paste("dfOut2_",order_idx,sep = "")
  assign(name_vec,dfOut2,envir = globalenv())
  
  if(order_idx == Order_of_interest[1]){
    dfOut3 <- dfOut2
  }else{
    dfOut3 <- rbind.data.frame(dfOut3,dfOut2)
  }
}
#####

level_vec <- unique(dfOut3$kegg.vec)[!(unique(dfOut3$kegg.vec) %in% c("Unclassified","Other"))]

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- level_vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut3)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut3))
    }
    
    if(dfOut3$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut3$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut3$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(level_vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == level_vec[i]]
    
    level_vec[i] <- vec
  }
  
  dfOut3$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut3 <- dfOut3[!(dfOut3$kegg.vec %in% c("Unclassified","Other")),]

p7 <- ggplot(dfOut3)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",level_vec)
                             ),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1")))+
  facet_wrap(facets = "Facet_name",
             nrow = 2,
             ncol = 2,
             scales = "free_y")+
  labs(title = "Orders",
       y = "Fraction of TPM",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "Pathway"),
         alpha = "none",
         color = guide_legend(title = "Shape"))

p7

save_name <- "KO_plots/FourEuk_topKO.png"
ggsave(save_name,width = 10,height = 5,dpi = 300)
```

```{r}

Euk.Sub <- Full.merged[Full.merged$Domain == "Eukaryota",]
Bact.Sub <- Full.merged[Full.merged$Domain == "Bacteria",]

# Clearning up the Bacteria Order names
# sort(unique(Bact.Sub$Order))

Bact.Sub$Order <- unlist(lapply(Bact.Sub$Order,function(x){unlist(strsplit(x,split = " "))[1]}))

filter <- is.na(Bact.Sub$Order)
Bact.Sub$Order[filter] <- "Uncategorized"

# sort(unique(Bact.Sub$Order))

# Clearning up the Eukaryote Order names

# sort(unique(Euk.Sub$Order))

Euk.Sub$Order <- unlist(lapply(Euk.Sub$Order,function(x){unlist(strsplit(x,split = "_"))[1]}))

filter <- Euk.Sub$Order == "Dino-Group-II"

Euk.Sub$Order <- unlist(lapply(Euk.Sub$Order,function(x){unlist(strsplit(x,split = "-"))[1]}))
Euk.Sub$Order[filter] <- "Dino-Group-II"

filter <- is.na(Euk.Sub$Order)
Euk.Sub$Order[filter] <- "Uncategorized"

# sort(unique(Euk.Sub$Order))

# Counting up the Eukaryote orders.####

Euk_Orders <- unique(Euk.Sub$Order)
n <- length(Euk_Orders)

day_vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day_vec)

for(i in 1:n){
  
  Order_filter <- Euk.Sub$Order == Euk_Orders[i]
  df_temp <- Euk.Sub[Order_filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df_count <- data.frame(matrix(ncol = m,nrow = n))
      names(df_count) <- meta.data$SampleName
      
      df_count <- cbind.data.frame(df_count,Euk_Orders)
    }
    
    df_count[i,j] <- sum(df_temp[,day_vec[j]])
    
  }
  
  if(i == n & j == m){
    df_count$Domain <- "Eukaryote"
    names(df_count)[names(df_count) == "Euk_Orders"] <- "Order"
  }
}

# Counting up the bacteria orders.####

Bact_Orders <- unique(Bact.Sub$Order)
n <- length(Bact_Orders)

day_vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day_vec)

for(i in 1:n){
  
  Order_filter <- Bact.Sub$Order == Bact_Orders[i]
  df_temp <- Bact.Sub[Order_filter,]
  
  for(j in 1:m){
    if(i == 1 & j == 1){
      df_count2 <- data.frame(matrix(ncol = m,nrow = n))
      names(df_count2) <- meta.data$SampleName
      
      df_count2 <- cbind.data.frame(df_count2,Bact_Orders)
    }
    
    df_count2[i,j] <- sum(df_temp[,day_vec[j]])
    
  }
  
  if(i == n & j == m){
    df_count2$Domain <- "Bacteria"
    names(df_count2)[names(df_count2) == "Bact_Orders"] <- "Order"
  }
}

#-------------------------------------------------------------------------------

dfOut <- rbind.data.frame(df_count,df_count2)

Euk_length <- nrow(df_count)
Bact_length <- nrow(df_count2)

for(i in 1:Euk_length){
  if(i == 1){
    out_n <- 1
    
    df_reg <- matrix(NA,
                     nrow = Euk_length*Bact_length,
                     ncol = 5)
    
    colnames(df_reg) <- c("R2","n_nonzero_Bact","n_nonzero_Euk","Bacteria","Eukaryote")
  }
  
  Euk_vec <- unlist(df_count[i,1:24])
  Euk_name <- df_count[i,25]
  
  for(j in 1:Bact_length){
    
    Bact_vec <- unlist(df_count2[j,1:24])
    Bact_name <- df_count2[j,25]
    
    lm_vec <- lm(Euk_vec~Bact_vec)
    
    R2 <- summary(lm_vec)$r.squared
    
    df_reg[out_n,1] <- round(R2,3)
    df_reg[out_n,2] <- sum(Bact_vec > 0)
    df_reg[out_n,3] <- sum(Euk_vec > 0)
    df_reg[out_n,4] <- Bact_name
    df_reg[out_n,5] <- Euk_name
   
    if(R2 >= .8){
      
      plot(Bact_vec,
           Euk_vec,
           ylab = Euk_name,
           # ylab = topkos_w_info$class[topkos_w_info$top_kos == Euk_name],
           xlab = Bact_name,
             main = paste("R2 =",round(R2,3)))

      abline(lm_vec)
    }
    
    
    out_n <- out_n+1 
  }
}

```

```{r}
dfOut <- rbind.data.frame(df_count,df_count2)

First_length <- nrow(dfOut)
Second_length <- nrow(dfOut)

for(i in 1:First_length){
  if(i == 1){
    out_n <- 1
    
    df_reg <- matrix(NA,
                     nrow = First_length*Second_length,
                     ncol = 3)
    
    colnames(df_reg) <- c("R2","First","Second")
  }
  
  Euk_vec <- unlist(dfOut[i,1:24])
  Euk_name <- paste(dfOut[i,25],dfOut[i,26])
  
  for(j in 1:Bact_length){
    
    if(j >= i){
      
    }else{
      Bact_vec <- unlist(dfOut[j,1:24])
      Bact_name <- paste(dfOut[j,25],dfOut[j,26])
      
      lm_vec <- lm(Euk_vec~Bact_vec)
      
      R2 <- summary(lm_vec)$r.squared
      
      df_reg[out_n,1] <- round(R2,3)
      df_reg[out_n,2] <- Bact_name
      df_reg[out_n,3] <- Euk_name
     
      if(R2 >= .8  & lm_vec$coefficients[2] != 0){
        
        plot(Bact_vec,
             Euk_vec,
             ylab = Euk_name,
             xlab = Bact_name,
             main = paste("R2 =",round(R2,3)))
  
        abline(lm_vec)
      }
      
      out_n <- out_n+1 
    }
    
  }
}
```
```{r}
# Kegg Path lookup####

Euk_KO_paths <- read.csv("KO_pathway_Euk.csv")

for(i in 1:nrow(Euk.Sub)){
  if(i == 1){
    Ko_path <- rep(NA,nrow(Euk.Sub))
  }

  vec <- Euk.Sub$KEGG1[i]

  vec_paths <- Euk_KO_paths$ko[Euk_KO_paths$K1 == vec]

  if(vec == "-"){
    vec_paths <- ""
  }

  if(vec_paths == ""){
    for(j in 2:length(KEGG_columns)){
      if(j == 2){
        stop_vec <- TRUE
      }

      if(stop_vec){
        vec <- Euk.Sub[i,KEGG_columns[j]]

        if(is.na(vec)){
          stop_vec <- FALSE
          vec_paths <- ""
        } else {
          vec_paths <- Euk_KO_paths$ko[Euk_KO_paths$K1 == vec]
        }

        if(vec_paths != ""){
          stop_vec <- FALSE
        }
      }
    }


  }
  if(vec_paths == ""){
    vec_paths <- "Unclassified"
  }

  Ko_path[i] <- vec_paths
}

Euk.Sub$K1_path <- Ko_path
```


```{r}

df.merged <- Euk.Sub

df.merged$K1_path <- Ko_path
kegg.vec <- unique(df.merged$K1_path)

filter <- grepl("C",df.merged$COG_category)
df.merged <- df.merged[filter,]

n <- length(kegg.vec)

# df.merged <- df.merged[df.merged$K1_path != "Unclassified",]

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  kegg.filter <- df.merged$K1_path == kegg.vec[i]
  df.temp <- df.merged[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,kegg.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    # df.count[i,j] <- sum(df.temp[,day.vec[j]])
    
  }
}

#-------------------------------------------------------------------------------

df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:10]]

top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
# top5.filter <- df.count$kegg.vec %in% c(top5.vec)

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day1_morning",
               "Day2_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","kegg.vec"))

Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
  distinct(AssemblyGroup, .keep_all = TRUE)

names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"

dfOut2 <- merge(df.summ,Day.Time,by = "Day")

partime$norm.par <- partime$par / max(partime$par)

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- top5.vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut2)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut2))
    }
    
    if(dfOut2$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut2$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut2$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(top5.vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == top5.vec[i]]
    
    top5.vec[i] <- vec
  }
  
  dfOut2$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

p6 <- ggplot(dfOut2)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",top5.vec)),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1")))+
  labs(title = "Cog Category C, top kegg pathways, all Eukaryotes",
       y = "Fraction of TPM",
       x = "Time of sample",
       caption = "This is a caption")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none")

p6

save_name <- "KO_plots/Euk_Phot_COG_topKO_path.png"
ggsave(save_name,width = 10,height = 5,dpi = 300)
```

```{r}

df.merged <- Euk.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"

kegg.vec <- unique(df.merged$KEGG1)

filter <- grepl("C",df.merged$COG_category)
df.merged <- df.merged[filter,]

n <- length(kegg.vec)

# df.merged <- df.merged[df.merged$KEGG1 != "Unclassified",]

day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
m <- length(day.vec)

for(i in 1:n){ #Looping through the Classes to count the occurrences.
  
  kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
  df.temp <- df.merged[kegg.filter,]
  
  for(j in 1:m){ #Looping through the sampling time points.
    
   if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
     
     df.count <- data.frame(matrix(ncol = m, nrow = n))
     names(df.count) <- meta.data$SampleName
     
     df.count <- cbind(df.count,kegg.vec)
   }
    
    df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
    # df.count[i,j] <- sum(df.temp[,day.vec[j]])
    
  }
}

#-------------------------------------------------------------------------------

df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]

top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:10]]

top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
# top5.filter <- df.count$kegg.vec %in% c(top5.vec)

df.top5 <- df.count[top5.filter,]
df.other <- df.count[!top5.filter,]

df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))

order.vec <- c("Day1_afternoon",
               "Day1_evening",
               "Day1_night",
               "Day1_morning",
               "Day2_night",
               "Day2_morning",
               "Day2_afternoon",
               "Day2_evening")

dfOut <- pivot_longer(df.count2,
                      all_of(meta.data$SampleName),
                      names_to = "Day",
                      values_to = "Count") %>% 
  mutate(Count = as.numeric(Count))

dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)

df.summ <- summarySE(data = dfOut, "Count",
                     groupvars = c("Day","kegg.vec"))

Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
  distinct(AssemblyGroup, .keep_all = TRUE)

names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"

dfOut2 <- merge(df.summ,Day.Time,by = "Day")

partime$norm.par <- partime$par / max(partime$par)

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- top5.vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut2)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut2))
    }
    
    if(dfOut2$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut2$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut2$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(top5.vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == top5.vec[i]]
    
    top5.vec[i] <- vec
  }
  
  dfOut2$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut2 <- dfOut2[!(dfOut2$kegg.vec %in% c("Unclassified","Other")),]

p6 <- ggplot(dfOut2)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",top5.vec)),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1")))+
  labs(title = "Cog Category C, top keggs, all Eukaryotes",
       y = "Fraction of TPM",
       x = "Time of sample",
       caption = "This is a caption")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "kegg"),
         alpha = "none")

p6

save_name <- "KO_plots/Euk_Phot_COG_topKO.png"
ggsave(save_name,width = 10,height = 5,dpi = 300)
```

```{r}

Class_of_interest <- c("Bacillariophyta","Dinophyceae","Prymnesiophyceae","Cryptophyceae")
Order_of_interest <- c("Bacillariales","Cryptomonadales","Dinophysiales","Phaeocystales")
Genus_of_interest <- c("Paraglaciecola","Colwellia")

df.merged <- Euk.Sub

df.merged$KEGG1[df.merged$KEGG1 == "-"] <- "Unclassified"
df.merged$Order[is.na(df.merged$Order)] <- "Unclassified"

filter <- grepl("C",df.merged$COG_category)
df.merged <- df.merged[filter,]

#Counting TPM for keggs for each order of interest####
df.merged_copy <- df.merged
df.merged_NoNA <- df.merged_copy[!is.na(df.merged_copy$Order),]

for(order_idx in Order_of_interest){
  
  order_filter <- df.merged_NoNA$Order == order_idx
  
  df.merged <- df.merged_NoNA[order_filter,]
  
  kegg.vec <- unique(df.merged$KEGG1)
  
  n <- length(kegg.vec)
  
  day.vec <- paste(meta.data$SampleID,"_quant",sep = "")
  m <- length(day.vec)
  
  for(i in 1:n){ #Looping through the Classes to count the occurrences.
    
    kegg.filter <- df.merged$KEGG1 == kegg.vec[i]
    df.temp <- df.merged[kegg.filter,]
    
    for(j in 1:m){ #Looping through the sampling time points.
      
      if(i == 1 & j == 1){ #Sets up an empty data.frame to input the data
        
        df.count <- data.frame(matrix(ncol = m, nrow = n))
        names(df.count) <- meta.data$SampleName
        
        df.count <- cbind(df.count,kegg.vec)
      }
      
      df.count[i,j] <- sum(df.temp[,day.vec[j]])/sum(df.merged[,day.vec[j]])
      # df.count[i,j] <- sum(df.temp[,day.vec[j]])
      
    }
  }
  
  df.count2 <- df.count[df.count$kegg.vec != "Unclassified",]
  
  top5.vec <- df.count2$kegg.vec[order(apply(df.count2[,-ncol(df.count2)],1,sum),decreasing = TRUE)[1:5]]
  
  top5.filter <- df.count$kegg.vec %in% c(top5.vec,"Unclassified")
  # top5.filter <- df.count$kegg.vec %in% c(top5.vec)
  
  df.top5 <- df.count[top5.filter,]
  df.other <- df.count[!top5.filter,]
  
  df.count2 <- rbind(df.top5,c(colSums(df.other[,1:24]),"Other"))
  
  order.vec <- c("Day1_afternoon",
                 "Day1_evening",
                 "Day1_night",
                 "Day1_morning",
                 "Day2_night",
                 "Day2_morning",
                 "Day2_afternoon",
                 "Day2_evening")
  
  dfOut <- pivot_longer(df.count2,
                        all_of(meta.data$SampleName),
                        names_to = "Day",
                        values_to = "Count") %>% 
    mutate(Count = as.numeric(Count))
  
  dfOut$Day <- substring(dfOut$Day,1,nchar(dfOut$Day)-1)
  
  df.summ <- summarySE(data = dfOut, "Count",
                       groupvars = c("Day","kegg.vec"))
  
  Day.Time <- meta.data[,c("AssemblyGroup","datetime")] %>% 
    distinct(AssemblyGroup, .keep_all = TRUE)
  
  names(Day.Time)[names(Day.Time) == "AssemblyGroup"] <- "Day"
  
  dfOut2 <- merge(df.summ,Day.Time,by = "Day") %>% 
    mutate(Facet_name = order_idx)
  
  name_vec <- paste("dfOut2_",order_idx,sep = "")
  assign(name_vec,dfOut2,envir = globalenv())
  
  if(order_idx == Order_of_interest[1]){
    dfOut3 <- dfOut2
  }else{
    dfOut3 <- rbind.data.frame(dfOut3,dfOut2)
  }
}
#####

level_vec <- unique(dfOut3$kegg.vec)[!(unique(dfOut3$kegg.vec) %in% c("Unclassified","Other"))]

# Pathway names API-------------------------------------------------------------

Pathway_activate <- TRUE

if(Pathway_activate){
  source("pathway_API.R")
  
  top_kos <- level_vec
  
  name <- character(length=0)
  class <- character(length=0)
  rel_paths <- character(length=0)
  
  for(i in 1:length(top_kos)) {
    
    pathway <- pathway_API(top_kos[i])
    name[i] <- pathway$name
    class[i] <- pathway$class
    rel_paths[i] <- pathway$Rel_paths[1]
  }
  
  topkos_w_info <-data.frame(top_kos, name, class, rel_paths)
  
  for(i in 1:nrow(dfOut3)){
    if(i == 1){
      path_names <- rep(NA,nrow(dfOut3))
    }
    
    if(dfOut3$kegg.vec[i] %in% c("Unclassified","Other")){
      path_names[i] <- dfOut3$kegg.vec[i]
    }else{
      path_names[i] <- topkos_w_info$name[topkos_w_info$top_kos == dfOut3$kegg.vec[i]]
    }
  }
  
  for(i in 1:length(level_vec)){
    
    vec <- topkos_w_info$name[topkos_w_info$top_kos == level_vec[i]]
    
    level_vec[i] <- vec
  }
  
  dfOut3$kegg.vec <- path_names
}

# Create Plot ------------------------------------------------------------------

dfOut3 <- dfOut3[!(dfOut3$kegg.vec %in% c("Unclassified","Other")),]

p6 <- ggplot(dfOut3)+
  geom_bar(aes(fill = factor(kegg.vec,
                             levels = c("Unclassified","Other",level_vec)
                             ),
               y = Count,
               x = datetime),
           position = "stack", stat = "identity")+
  scale_x_continuous(breaks = unique(meta.data$datetime),
                     labels = unique(meta.data$AssemblyGroup))+
  scale_fill_manual(values = c(brewer.pal(12,"Set3"),
                               brewer.pal(8,"Set2"),
                               brewer.pal(9,"Set1"),
                               brewer.pal(9,"Paired")))+
  facet_wrap(facets = "Facet_name",
             nrow = 2,
             ncol = 2,
             scales = "free_y")+
  labs(title = "Cog Category C, top keggs",
       y = "Fraction of TPM",
       x = "Time of sample")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust=1))+
  guides(fill = guide_legend(title = "Pathway"),
         alpha = "none",
         color = guide_legend(title = "Shape"))

p6

save_name <- "KO_plots/FourEuk_Phot_COG_topKO.png"
ggsave(save_name,width = 12,height = 5,dpi = 300)
```


```{r}

top_kos <- kegg.vec[5:15]

for(i in 1:length(top_kos)) {
    pathway <- system(paste0("curl https://rest.kegg.jp/get/", top_kos[[i]]), intern=TRUE)
    
    print(pathway[4])
    # name[[i]] <- pathway[[4]]
    # class[[i]] <-pathway[[5]]
}

pathway_API <- function(input){
  pathway <- system(paste0("curl https://rest.kegg.jp/get/", input), intern=TRUE)
  
  Name_idx <- grep("NAME",pathway)
  Class_idx <- grep("CLASS",pathway)
  
  RelPaths_idx <- grep("REL_PATHWAY",pathway)
  RelPaths_end <- grep("///",pathway)-1
  
  name <- ifelse(isEmpty(Name_idx),
                 NA,
                 sub("^\\S+\\s+", "", pathway[Name_idx]))
  
  class <- ifelse(isEmpty(Class_idx),
                  NA,
                  sub("^\\S+\\s+", "", pathway[Class_idx]))
  
  # RelPaths <- ifelse(isEmpty(RelPaths_idx),
  #                    NA,
  #                    sub(".*\\sko", "ko", pathway[RelPaths_idx:RelPaths_end]))
  
  if(!isEmpty(RelPaths_idx)){
    RelPaths <- sub(".*\\sko", "ko", pathway[RelPaths_idx:RelPaths_end])
  } else {
    RelPaths <- NA
  }
  
  # name <- sub("^\\S+\\s+", "", pathway[Name_idx])
  # class <- sub("^\\S+\\s+", "", pathway[Class_idx])
  # RelPaths <- sub(".*\\sko", "ko", pathway[RelPaths_idx:RelPaths_end])
  
  output <- list("ko" = input,
                 "name" = name,
                 "class" = class,
                 "Rel_paths" = RelPaths)
  
  return(output)
}

pathway_API("ko01522")
pathway_API("ko05220")

# kegg_API <- function(kegg){
#   pathway <- system(paste0("curl https://rest.kegg.jp/link/pathway/", kegg), intern=TRUE)
#   l <- length(pathway)
# 
#   ifelse(l != 0,
#          stri_sub(pathway[[l]], 16),
#          "NA")
# }


vec <- lapply(kegg.vec[5:15],pathway_API)

pathway <- system(paste0("curl https://rest.kegg.jp/get/", kegg.vec[11]), intern=TRUE)
grep("NAME",pathway)

kegg_API(koslist[1])

vec <- system(paste0("curl https://rest.kegg.jp/link/pathway/", koslist[1]), intern=TRUE)

vec2 <- lapply(substring(vec,16)[grep("ko",substring(vec,16))],pathway_API)
sapply(vec2,getElement,"Rel_paths")


for(i in 1:length(vec2)){
  n <- length(vec2[[i]]$Rel_paths)
  print(vec2[[i]]$Rel_paths[n])
}

```

