---
title: "Row_analysis"
author: "Andreas Norlin"
date: "2024-08-22"
output: html_document
---

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)

#rm(list = ls())

package.list <- c("dplyr","tidyverse","ggplot2","lemon","vegan","Rmisc","lubridate")

if(!all(package.list %in% installed.packages()[,"Package"])){
  install.packages(package.list[!(package.list %in% installed.packages()[,"Package"])])
}

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lemon)
library(vegan)
library(Rmisc)
library(lubridate)

#Loading the meta.data: meta.data1 is the Assmebly group and the sequencing ID (sample ID),
#meta.data2 is the data about sampling time and site.

meta.data1 <- read.csv("CSV_files/dielRNA_eukrythmic.tsv", sep = "\t")
meta.data2 <- read.csv("sample_metadata.csv") %>% 
  mutate(Sample_ID = paste("HM",Sample_ID,sep = ""))

names(meta.data2)[names(meta.data2) == "Sample_ID"] <- "SampleID"

#Combining meta.data1 and meta.data2 and making the lubri string a data + time saved in datetime
meta.data <- merge(meta.data1,meta.data2,by = "SampleID") %>% 
  mutate(datetime = ymd(substring(lubri,1,10))+hms(substring(lubri,12,19)))

meta.data <- separate(meta.data, col = AssemblyGroup, into = c("Day.num","ToD"),sep = "_",remove = FALSE, fill = "right", extra = "drop")

# meta.data$lubri <- with_tz(mdy_hms(meta.data$datetime, tz = "UTC"),
#                            tz = "America/Santiago")

COG_categories <- read.csv("COG_categories.csv",sep = ",")

Eukaryota.merged <- read.csv("CSV_files/Eukaryota.merged.csv")

par1 <- read.delim("NBP2113pguv.d342",  sep = " ", header =FALSE)
par2<- read.delim("NBP2113pguv.d343",  sep = " ", header =FALSE)
par3<- read.delim("NBP2113pguv.d344",  sep = " ", header =FALSE)

par = rbind(par1, par2, par3)[-1,c(1,2,3,10)]
names(par) <- c("juliendatetime","date", "time", "par")

partime <- par %>% 
  separate(juliendatetime, c("yearday","hour", "min", "sec"), sep = ":" ) %>% 
  unite(utctime, hour, min, sec, sep=":")  %>% 
  mutate(utcdatetime = paste(date, utctime))

partime$lubri <- with_tz(mdy_hms(partime$utcdatetime, tz = "UTC"),
                         tz = "America/Santiago")

for(i in 1:nrow(meta.data)){

  filter.above <- partime$lubri >= meta.data$datetime[i]
  filter.below <- partime$lubri < meta.data$datetime[i]
  
  vec.above <- partime[partime$lubri == min(partime$lubri[filter.above]),]
  vec.below <- partime[partime$lubri == max(partime$lubri[filter.below]),]
  
  meta.data$par[i] <- mean(vec.above$par,vec.below$par)
  
}

create_plot = function(x_vec,y_vec,lm_vec){
  plot(x_vec,y_vec)
  abline(lm_vec)
}
```


```{r}
Input_data <- Eukaryota.merged[1:100000,]
# Input_data <- read.csv("CSV_files/Bacteria.subsection.TPM.csv")

vec_assembly <- unique(meta.data$AssemblyGroup)

for(i in 1:length(vec_assembly)){
  if(i == 1){
    names(Input_data) <- unlist(lapply(names(Input_data),
                                       function(x){unlist(strsplit(x,
                                                                   split = "_",
                                                                   fixed = TRUE))[1]}))
    
    df_meta <- meta.data[,c("SampleID","par","AssemblyGroup")]
    
    df_means <- Input_data$SequenceID
    par_vec <- NA
    time1 <- Sys.time()
  }
  
  df_temp <- Input_data[,meta.data$SampleID[meta.data$AssemblyGroup == vec_assembly[i]]]
  
  meta_temp <- df_meta %>% 
    distinct(AssemblyGroup,.keep_all = TRUE) %>% 
    filter(AssemblyGroup == vec_assembly[i])
  
  par_vec[i] <- meta_temp$par
  
  vec <- rowMeans(df_temp)
  df_means <- cbind.data.frame(df_means,vec)
  
  names(df_means)[i+1] <- vec_assembly[i]
  
  if(i == length(vec_assembly)){
    # df_means <- as.data.frame(t(df_means))
    names(df_means)[1] <- "SequenceID"
    
    df_means$r.squared <- apply(df_means[,2:9],1,function(row){summary(lm(row~par_vec))$r.squared})
    df_means$n_nonzero <- apply(df_means[,2:9],1,function(row){sum(row > 0)})
    df_means$p_value <- apply(df_means[,2:9],1,function(row){summary(lm(row~par_vec))$coefficients[2,4]})
    
    df_means$KEGG1 <- unlist(lapply(Input_data$KEGG,function(x){unlist(strsplit(x,","))[1]}))
    
    seq_df <- df_means[df_means$r.squared >.95 & df_means$n_nonzero > 2,]
    
    print(Sys.time() - time1)
  }
}
```
```{r}
kegg_API <- function(kegg,First_path = TRUE){
  pathway <- system(paste0("curl https://rest.kegg.jp/link/pathway/", kegg), intern=TRUE)
  path_idx <- grep(paste0(kegg,"\tpath:ko"),pathway)

  ifelse(isEmpty(path_idx),
         "-",
         stri_sub(pathway[ifelse(First_path,min(path_idx),max(path_idx))], 16))
}

seq_df$K1_path <- laply(seq_df$KEGG1,function(x){ifelse(x != "-",kegg_API(x,F),"-")})

par_paths <- unique(seq_df$K1_path[seq_df$K1_path != "-"])

save(par_paths,file = "par_paths.RData")
```

```{r}
df_means$fold_change <- log(df_means$Day1_afternoon+0.0001 / (df_means$Day2_evening+0.0001),2)

plot(df_means$fold_change,-log(df_means$p_value,10))
```


```{r}
Input_data <- Eukaryota.merged[1:1000,]
# Input_data <- read.csv("CSV_files/Bacteria.subsection.TPM.csv")

```


```{r}
# seq_df <- read.csv("CSV_files/Eukaryota_row_reg.csv")
filter <- Eukaryota.merged$SequenceID %in% seq_df$SequenceID
Eukaryota_light <- Eukaryota.merged[filter,]
dfOut <- Eukaryota_light


# Create a bar plot
ggplot(dfOut, aes(x = Class))+
  geom_bar(aes(y = after_stat(count)/sum(after_stat(count))))+
  labs(title = "Class Distribution",
       x = "Class",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# ggsave("Light_correlated_Class.png",dpi = 300,height = 5, width = 6)

# Create a bar plot
ggplot(Eukaryota.merged, aes(x = Class))+
  geom_bar(aes(y = after_stat(count)/sum(after_stat(count))))+
  labs(title = "Class Distribution",
       x = "Class",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# ggsave("All_Class.png",dpi = 300,height = 5, width = 6)
```

```{r}
seq_df <- read.csv("CSV_files/Bacteria_row_reg.csv")
Bacteria.TFA <- read.csv("CSV_files/Bacteria.TFA_NoRep.csv")

filter <- Bacteria.TFA$SequenceID %in% names(seq_df)
Bacteria_light <- Bacteria.TFA[filter,]

dfOut <- Bacteria_light

# Create a bar plot
ggplot(dfOut, aes(x = Class))+
  geom_bar(aes(y = after_stat(count)/sum(after_stat(count))))+
  labs(title = "Class Distribution",
       x = "Class",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# ggsave("Light_correlated_Class.png",dpi = 300,height = 5, width = 6)

# Create a bar plot
ggplot(Bacteria.TFA, aes(x = Class))+
  geom_bar(aes(y = after_stat(count)/sum(after_stat(count))))+
  labs(title = "Class Distribution",
       x = "Class",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# ggsave("All_Class.png",dpi = 300,height = 5, width = 6)
```